### DISCUSSION TITLE
Yaml formatting in VS code

### DISCUSSION THREAD

**Discussion by TsvetomirValchev** [redhat-developer/vscode-yaml#1017] [Q&A]
So I have a yaml configuration like:

```
plan:
      - in_parallel: &default-job-aggregate
        - get: something1
          passed: [some-setup]
          trigger: true
        - get: test
          trigger: false
        - get: test-env-image
          trigger: false
      - get: something2
        passed: [some-setup]
        trigger: true 
```

After I run the Formatting command in VS code on this yaml file using the red-hat yaml formatter as a default formatter the yaml is formatted like:

```
    plan:
      - in_parallel: &default-job-aggregate
          - get: something1
            passed: [some-setup]
            trigger: true
          - get: test
            trigger: false
          - get: something2
            trigger: false
      - get: manual-trigger
        passed: [some-setup]
        trigger: true
```
        
It seems to be adding 1 more tabulation and I could not find a way to modify that behaviour. I only found a way to configure how many "spacebars" one press of "tab" equals to but that doesn't seem to fix my issue as it still puts 2 spaces instead of one even then.  

Also another thing:
Is there a way to disable "force line-breaks on array items"? I don't want each of the items in the arrays to be on a new line.

Thanks!
