### DISCUSSION TITLE
Python double exclamation

### DISCUSSION THREAD

**Discussion by metal3d** [redhat-developer/vscode-yaml#1059] [Q&A]
Hello,

Using Mkdocs with Material, the YAML file should sometimes use this:

```yaml
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

But... NeoVim with nvim-lspconfig fails to accept the `!!python` tag:

![image](https://github.com/user-attachments/assets/13550e63-84bc-4ec4-a168-84243ff2032d)

I tried many configurations... 

- Adding `tag:yaml.org,2002:python`
- Adding `tag:yaml.org,2002:python/name`
- Adding `!python`
- Adding `!python/name`
- Adding `!python/name scalar`

And a dozen of others. This fails. Yamls-language-server continuously says that there is an error in the YAML file.

This is the configuration I have now, still doesn't work:

```lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        yamlls = {
          settings = {
            yaml = {
              validate = true,
              customTags = { "!!python/name" },
            },
          },
        },
      },
    },
  },
}
```

Thanks if someone can help me.
