### DISCUSSION TITLE
Associating a schema with a subset of a file

### DISCUSSION THREAD

**Discussion by kujon** [redhat-developer/vscode-yaml#1127] [General]
Hello Folks 👋 

I've got a YAML that looks something like this:
```yaml
stuff:
 - type: foo
   properties:
     hello: iamastring
 - type: bar
   properties:
     haha: 42
```

The thing is that the shape of `properties` changes depending on the `type`.  I am aware of `# yaml-language-server` directive, but that changes the schema for the whole file, rather than a subset of it. I would like to do something similar to `kustomize`'s `$ref` comments, where I can tell it to treat part of the file according to one schema, and another part according to another schema. Is this possible? If yes, is this the extension's feature, or the language server feature? 

Context: I'm writing an extension myself for dealing with this type of yaml, and I would like to stand on the shoulders of giants (a.k.a. you), rather than create every completions provider, etc, myself.
