### DISCUSSION TITLE
I've Installed the Plugin - Nothing Happens

### DISCUSSION THREAD

**Discussion by Fosol** [redhat-developer/vscode-yaml#754] [Q&A]
Anyone have a tutorial to install and get working?

I've installed the plugin, but it doesn't do anything.

I have no intelli-sense available in my yaml files.

I'd also love to have Openshift schema loaded.

**Comment by gorkem** [comment]
Your setup is probably missing a schema association. This extension needs to have a [mapping](https://github.com/redhat-developer/vscode-yaml#associating-a-schema-to-a-glob-pattern-via-yamlschemas) that tells the extension which schema to use. We do have a built-in schema for `Kubernetes`, which you can configure as described on the README.

**Comment by agreedSkiing** [comment]
@gorkem 
So....

Well no Hi!

How do I configure this plugin to give me intellisens andexplenations for openshift/kubernates based yamls? And maybe Istio/Maistra also since that I something I use regularly.

I have tried the settings down below to get it to work and yes it works in my kustomization.yaml but no where else :(
```json
    "yaml.completion": true,
    "yaml.format.enable": false,
    "yaml.schemaStore.enable": true,
    "yaml.schemas": {
          "https://json.schemastore.org/kustomization.json": "kustomization.yaml",
          "Kubernetes": "/*.yaml"
    }
```

Those settings have been tried it in a strategic merge yaml file (a file that is used in the `patchStrategicMerge:` section of my kustomization.yaml) and its deployment base file.
#### Strategic merge yaml file
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-cmc-admin
spec:
  template:
    spec:
      containers:
        - name: ca-cmc-admin
          volumeMounts:
            - name: ca-cmc-admin-properties
              mountPath: /opt/ca-cmc-admin/
            - name: ca-cmc-admin-cmc-crt
              mountPath: /opt/ca-cmc-admin/cmc/
            - name: ca-cmc-admin-jks
              mountPath: /opt/ca-cmc-admin/keystore/
      volumes:
        - name: ca-cmc-admin-cmc-crt
          configMap:
            name: ca-cmc-admin-crt
        - name: ca-cmc-admin-properties
          configMap:
            name: ca-cmc-admin-properties
        - name: ca-cmc-admin-jks
          configMap:
            name: ca-cmc-admin-jks
```
#### Base deployment yaml file
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ca-cmc-admin
    app.openshift.io/runtime: spring-boot
  name: ca-cmc-admin
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: ca-cmc-admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ca-cmc-admin
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: base
          name: ca-cmc-admin
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          image: always:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
```

I just feel like I can't be the only one having problems with this configuration and to my knowledge I'm not the only one in my company that has these problem, and if you point me to the https://github.com/redhat-developer/vscode-yaml#associating-schemas explain this section to me like I'm a five year old.
