### DISCUSSION TITLE
Sequence of Mappings Formatting

### DISCUSSION THREAD

**Discussion by Jetbo** [redhat-developer/vscode-yaml#918] [Q&A]
Hello, I'm trying to figure out how to get this extension to respect the non-compact format of YAML sequence of mappings. This is valid YAML under official 1.2 [spec](https://yaml.org/spec/1.2.2/#21-collections) (see Example 2.4).

The problem is the formatter always converts it to the **compact** version.

**compact**:
```yaml
sequence:
  - a: 1
    b: 2
  - a: 1
    b: 2
```

**non-compact**:
```yaml
sequence:
  - 
     a: 1
     b: 2
  - 
     a: 1
     b: 2
```

[This even shown in the official extension gif](https://github.com/redhat-developer/vscode-yaml/blob/main/images/demo.gif):

![image](https://user-images.githubusercontent.com/7456929/230180819-a04a626f-f70e-46ad-a4e4-65afaa80c4bf.png)

How can I do this?
