### DISCUSSION TITLE
Cluster API CRDs not supported

### DISCUSSION THREAD

**Discussion by guettli** [redhat-developer/vscode-yaml#928] [Q&A]
I have a yaml likek this:

```
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "foo-control-plane"
spec:
  replicas: 1
  kubeadmConfigSpecxxx:
    clusterConfiguration:
```

I added a typo on purpose: "kubeadmConfigSpecxxx".

I was hoping to see a warning, but this did not show.

It seems that the yaml is not detected.

How to debug this?

Is there a way to see if the yaml plugin found a schema?

How to add the schema, if the plugin does not know it up to now?
