### DISCUSSION TITLE
Missing schema for eksctl

### DISCUSSION THREAD

**Discussion by SoerenHenning** [redhat-developer/vscode-yaml#942] [Q&A]
Consider the following file from the [eksctl docs](https://eksctl.io/usage/creating-and-managing-clusters/):

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-north-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub
```

When opening that file in VS Code with the YAML extension, I am not able the set the schema to the eksctl one as simply does not show up in the drop-down list. There is a schema available in the JSON Schema Store: https://www.schemastore.org/api/json/catalog.json And the option to *Automatically pull available YAML schemas from the JSON Schema Store*  is ticked in my installation. What could be the issue here?
