### DISCUSSION TITLE
Is there a way to allow ERB in a YAML file without highlight errors?

### DISCUSSION THREAD

**Discussion by onathjan** [redhat-developer/vscode-yaml#997] [Q&A]
I'm working on a Rails app and in my user.yml fixture lines 1 and 8 of the following code are highlighted as errors even though it is valid ERB. Is there a way to have the YAML validator overlook ERB without turning off validations completely? 

For reference the error for the first line is `Implicit keys need to be on a single line` and the error for the second line is `Implicit map keys need to be followed by map values`.

```
<% 30.times do |n| %>
user_<%= n %>:
  name:  <%= "User #{n}" %>
  email: <%= "user-#{n}@example.com" %>
  password_digest: <%= User.digest('password') %>
  activated: true
  activated_at: <%= Time.zone.now %>
<% end %>
```

**Comment by jdelStrother** [comment]
One option is to "comment" out the erb lines. The erb expressions still get evaluated, it just makes them invisible to the yaml parser.

```yaml
# <% 30.times do |n| %>
user_<%= n %>:
  name:  <%= "User #{n}" %>
  email: <%= "user-#{n}@example.com" %>
  password_digest: <%= User.digest('password') %>
  activated: true
  activated_at: <%= Time.zone.now %>
# <% end %>
```

I don't love it though, it makes it very easy to skip over the erb lines when reading.
