### ISSUE TITLE
Invalid error Map keys must be uniqueYAML on mutliple merges

### ISSUE THREAD

**Issue by AlexisColes** [redhat-developer/vscode-yaml#1005]
## Describe the bug

```
dind: &dind
  image: 117771453557.dkr.ecr.eu-west-1.amazonaws.com/github-actions-runner-dind:15
  container_mode: false
  dindMode: true

c-2: &c2
  resources: 
    requests:
      cpu: 2
      memory: 4Gi
      
runners:
  c-2-dind:
    <<: *dind
    <<: *c2
    min_replicas: 2
```
This is valid yaml!

however the line `<<: *c2` is marked as an error "Map keys must be uniqueYAML on mutliple merges" 

![image](https://github.com/redhat-developer/vscode-yaml/assets/8488871/48cfae71-136a-4d29-833f-78dd5ae3659b)

## Expected Behavior

It should not flag this as an error.

## Current Behavior

If flags it as an error

## Steps to Reproduce

1. put the above yaml into vscode with this extension loaded.
2.
3. 

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)
