### ISSUE TITLE
source.toolkit.fluxcd.io manifest with name prometheus.yaml error: Request vscode/content failed unexpectedly without providing any details.YAML(768)

### ISSUE THREAD

**Issue by gmarcot** [redhat-developer/vscode-yaml#1013]
## Describe the bug

i have a manifest file name: prometheus.yaml and , by default, the extension point to schema https://json.schemastore.org/prometheus.json but it's not my case because this a manifest relate to kind HelmRepository.
This is the content:

```
cat prometheus.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
spec:
  interval: 24h0m0s
  url: https://prometheus-community.github.io/helm-charts
```
  

## Expected Behavior
the file contents are not marked as error

## Current Behavior

Unable to load schema from 'https://json.schemastore.org/prometheus.json': Request vscode/content failed unexpectedly without providing any details.YAML(768)

## Steps to Reproduce

1. create a file with name : prometheus.yaml
2. add this content or any others type of contents like:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
spec:
  interval: 24h0m0s
  url: https://prometheus-community.github.io/helm-charts
```
3.  Open the file in vscode and see the error
## Environment
- [ X] Windows
- [ ] Mac
- [ X] Linux
- [ ] other (please specify)
