### ISSUE TITLE
Default formatter not being set

### ISSUE THREAD

**Issue by mxcury** [redhat-developer/vscode-yaml#1041]
## Describe the bug
I have installed the Prettier for formatting my html, css, ... but I would like to use the Redhat YAML extension for formatting .yaml files however, when I attempt to select this extension as the default formatter I still get a warning that there is no default formatter for .yaml files. 

It makes the change in the `settings.json` but it is not reflected in the editor window itself. 
```
	"[yaml]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
```	
-->

## Expected Behavior
It should display in the editor window that there is a configured default formatter for .yaml files

## Current Behavior
I receive the warning in the status bar that: "There are multiple formatters for 'YAML' file. One of them should be configured as the default formatter
<img width="1188" alt="Screenshot 2024-07-13 at 12 22 05" src="https://github.com/user-attachments/assets/c8f0adee-3fee-42e3-bc3b-b97330090ca7">

## Steps to Reproduce
1. Install both the [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and [YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension
2. Create a new .yaml file in an empty directory, containing the following schema
```
name: John Doe
age: 30
is_student: false
courses:
- Mathematics
  - Physics
  - Computer Science
address:
  street: 123 Main St
  city: Anytown
  state: CA
  postal_code: 12345
```
3. Attempt to set the default formatter to YAML and observe the change the `settings.json`

## Environment
- [ ] Windows
- [X] Mac
- [ ] Linux
- [ ] other (please specify)
