### ISSUE TITLE
Arrays of objects are not split up in the yaml outline

### ISSUE THREAD

**Issue by nicholas-devlin** [redhat-developer/vscode-yaml#106]
Here is an example image: https://cl.ly/0d3J3r3R202l

The text:

```yaml
init_config:
  
instances:
  - name:  words
    url:   http://localhost:8080/
    http_response_status_code: 200
    timeout: 5
    skip_event: true
    tags:
      - name:words
      - type:app
      - env:prod
  - name:  words2
    url:   http://localhost:8081/
    http_response_status_code: 200
    timeout: 5
    skip_event: true
    tags:
      - name:words2
      - type:app
      - env:prod
```

`instances` just appearing as an array with a bunch of duplicate values. http://yaml-online-parser.appspot.com/ seems to correctly parse this as:

```json
{
  "instances": [
    {
      "http_response_status_code": 200, 
      "name": "erights http://localhost:8080/", 
      "timeout": 5, 
      "tags": [
        "name:erights", 
        "type:app", 
        "env:prod"
      ], 
      "url": "http://localhost:8080/", 
      "skip_event": true
    }, 
    {
      "http_response_status_code": 200, 
      "name": "erights http://localhost:8080/", 
      "timeout": 5, 
      "tags": [
        "name:erights", 
        "type:app", 
        "env:prod"
      ], 
      "url": "http://localhost:8080/", 
      "skip_event": true
    }
  ], 
  "init_config": null
}
```
