### ISSUE TITLE
.gitlab-ci.yml validation errors

### ISSUE THREAD

**Issue by adam-moss** [redhat-developer/vscode-yaml#110]
Hi,

I'm seeing errors in the validation of `.gitlab-ci.yml` files, specifically anchors, as described in https://github.com/redhat-developer/vscode-yaml/issues/60.

However, as per https://github.com/redhat-developer/vscode-yaml/issues/87, this doesn't happen if I rename the file to `.yaml` where it validates correctly.

Interestingly it does appear to be using the correct schema for validation, just not recognising the anchor is an anchor, and therefore complaining about missing attributes that would otherwise be mandatory.

Thanks.

**Comment by JPinkney** [comment]
So everything is working correctly when the file is named .yaml but not when it’s named .yml?

**Comment by adam-moss** [comment]
It appears to, yes

**Comment by sebbuku** [comment]
Same thing with .circleci/config.yml. It validates if I rename it to config.yaml.

**Comment by matalo33** [comment]
Confirmed this issue is still present

MacOS
VSCode Version 1.32.3 (1.32.3)
yaml 0.4.0

**Comment by jghal** [comment]
This is still an issue for me on Amazon Linux 2. But using same version of WSL and YAML plugin on Windows 10 or Windows 10 Remote to WSL Ubuntu 18.04 I don't see the issue.

VSCode 1.38.1
YAML plugin 0.5.3

**Comment by robmurtagh** [comment]
I'm also seeing this issue:

OS: MacOS Catalina
VSCode Version: 1.39.2
YAML Plugin: 0.5.3

Thanks in advance for reviewing

**Comment by JPinkney** [comment]
Ah I see why. I think some schemas in the schema store api only set their files to match *.yml. For example in http://schemastore.org/api/json/catalog.json gitlab is only set to match `.gitlab-ci.yml` right now. 

For now if you don't want to change your file name you'll have to do:

```
yaml.schemas: {
    "http://json.schemastore.org/gitlab-ci": ".gitlab-ci.yaml"
}
```

**Comment by adam-moss** [comment]
Not sure this is correct?

`.gitlab-ci.yml` is the correct file name, it is the linter that only works if you rename it to `yaml`

**Comment by faisal6621** [comment]
I am also having the same issue:

VSCode: 
  Version: 1.41.1 (system setup)
  Commit: 26076a4de974ead31f97692a0d32f90d735645c0
  Date: 2019-12-18T14:58:56.166Z
  Electron: 6.1.5
  Chrome: 76.0.3809.146
  Node.js: 12.4.0
  V8: 7.6.303.31-electron.0
  OS: Windows_NT x64 10.0.17134
YAML Plugin: 0.6.1

**Comment by faisal6621** [comment]
Hi @adam-moss,
Are you facing this issue with [YAML Anchors](https://docs.gitlab.com/ee/ci/yaml/README.html#anchors)? If yes, try [extends](https://docs.gitlab.com/ee/ci/yaml/README.html#extends) which is introduced in GitLab 11.3.

cc: @JPinkney

**Comment by TBBle** [comment]
Those are only substitutes if the YAML Anchors are being used to extend a particular job. It doesn't work for [YAML anchors for `before_script` and `after_script`](https://docs.gitlab.com/ee/ci/yaml/README.html#yaml-anchors-for-before_script-and-after_script) for example when used in top-level `before_script`, rather than per-job `before_script`.

Once we start using the replacement 'default' job, it's not clear if that will support 'extends' in this way.

**Comment by Morriz** [comment]
Can we get an update to such a simple problem?

**Comment by inostia** [comment]
Seeing this specifically when using anchor definitions for gitlab ci scripts, per instructions here: https://docs.gitlab.com/ee/ci/yaml/#yaml-anchors-for-script

I get the same validation issues.

**Comment by JPinkney** [comment]
Can someone post a yaml file so I can confirm this is working in the pre-release.

Or can someone try with the latest pre-release: https://github.com/redhat-developer/vscode-yaml/releases

**Comment by joelmgallant** [comment]
@JPinkney - confirmed this behavior can be reproduced on 0.7.2 release.

**Comment by JPinkney** [comment]
@joelmgallant If it is not working correctly can you post your YAML so I can diagnose the issue

**Comment by joelmgallant** [comment]
@JPinkney - of course, thanks for investigating!

Here's a minimal reproduction case:
```
image: a-docker-image

stages:
  - merge-create

# Should be valid, highlighted as incorrect type error
.do-anchor-tasks: &do-anchor-tasks
- ls -lah

merge-create-task:
  stage: merge-create
  when: manual
  script:
    - *do-anchor-tasks
```

Changing this file to `.yaml` instead of `.yml` highlights as expected.

**Comment by laymonage** [comment]
This issue also raises `Property << is not allowed.` when using merge keys. Changing the extension to `.yaml` "fixes" it but we need the file name to be `.gitlab-ci.yml`.

**Comment by JPinkney** [comment]
@laymonage Please post the yaml causing this issue and what version of vscode-yaml you are using

**Comment by laymonage** [comment]
> @laymonage Please post the yaml causing this issue and what version of vscode-yaml you are using

Here's an example:

```yaml
image: python:3.6

stages:
  - test

.disable_dev: &disable_dev
  except:
    - dev@user/repo

.cache_test: &cache_test
  <<: *disable_dev
  stage: test
  cache:
    key: test
    paths:
      - .cache/test

unittest:
  <<: *cache_test
  stage: test
  script:
    - echo "Hello, world!"
```

Merge key on `<<: *disable_dev` will throw `Property << is not allowed.` despite it's valid. I'm using the latest version (0.9.1) of vscode-yaml on Code-OSS 1.47.3.

**Comment by OutOfFocus4** [comment]
I am also having this issue in a Django project.

Visual Studio Code Information:
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

Using version 0.10.1 of the YAML extension.

Here is part of my `.gitlab-ci.yml`:

```yaml
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: "$CI_PROJECT_ID"
  paths:
    - .cache/pip
    - venv/

.Test: &test-template
  stage: test
  only:
    - master

.django-test: &django-template
  <<: *test-template  # Property << is not allowed.
  before_script:
    - echo "Not relevant"

.browser: &browser-template
  <<: *test-template  # Property << is not allowed.
  before_script:
    - echo "Not relevant"

# Other stuff below this validates
```
