### ISSUE TITLE
github ISSUE_TEMPLATE config.yml validation error

### ISSUE THREAD

**Issue by RSS1102** [redhat-developer/vscode-yaml#1107]
## Describe the bug

```
blank_issues_enabled: false
contact_links:
  - name:  issue-helper 
    url: https://xxxx
    about: this is  issue-helper .
```

## Expected Behavior

https://docs.github.com/zh/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser  There shouldn't be an error here.

![Image](https://github.com/user-attachments/assets/880eb21d-9680-4e3b-9c97-190cedf5423a)

## Current Behavior

![Image](https://github.com/user-attachments/assets/cb87529d-db7e-4546-8e0b-c36a3bebe466)

## Steps to Reproduce

1.
2.
3. 

## Environment
- [ ] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)
