### ISSUE TITLE
Remove Trailing Comma

### ISSUE THREAD

**Issue by man2machine** [redhat-developer/vscode-yaml#1112]
Currently the formatter always adds trailing commas. Is there a way to disable this?

**Comment by datho7561** [comment]
Here's a case where this would apply:

```yaml
{
  key: 'value',
  food: 'raisins',
  airport: 'YYZ',
  cheese_lung: 'comfortable',
  lightened_bulb: 'illuminating',
}
```

...formatted it should look like...

```yaml
{
  key: 'value',
  food: 'raisins',
  airport: 'YYZ',
  cheese_lung: 'comfortable',
  lightened_bulb: 'illuminating'
}
```

(let me know if I got this wrong)

Under the hood, this extension uses prettier to format YAML. Prettier supports this setting, so it should be possible to do this. The formatting setting works when running prettier from the CLI, but I haven't gotten it to work properly through the language server. I'll need to investigate it further.
