### ISSUE TITLE
Failure to gracefully handle empty items definitions on array properties

### ISSUE THREAD

**Issue by aramando** [redhat-developer/vscode-yaml#1121]
## Describe the bug

The extension generates exceptions when viewing, and fails to provide validation to, files that reference a schema defining an object with an array property that is missing a value for the items definition.

**file1.yaml**
```yaml
# yaml-language-server: $schema=http://json-schema.org/draft-07/schema#
$schema: 'http://json-schema.org/draft-07/schema#'

ObjectSchema:
  type: object
  properties:
    refProp:
      type: array
      items: # an array with an empty items property causes exceptions that break validation

```
**file2.yaml**
```yaml
# yaml-language-server: $schema=./file1.yaml#/ObjectSchema

refProp: true # should be highlighted as an incorrect type if validation is working 
```

## Expected Behavior
I would expect the empty `items:` property to be higlighted as invalid, assuming it is indeed invalid JSON-schema according to the schema set as the language server schema for file1. If it is not invalid (though I'm sure it must be), then it shouldn't cause a problem for the extension when loading it as part of parsing and validating file2.

## Current Behavior
Validation simply fails to function, and exceptions are thrown by the extension.

## Steps to Reproduce
1. Create the two files shown above
2. Open file2 and observe the failure to highlight the error of the invalid property value type.
3. Open VS Code's Output pane and set the content to Window, then hover over the refProp name, observe the exception that is generated by the extension. 
4. Now comment out the `items:` line in file1 (or provide a valid item spec), restart the extension host to load the updated schema and go back to file2 and note that validation is now working as expected.

## Environment
- [ ] Windows
- [X] Mac
- [ ] Linux
- [ ] other (please specify)

Extension version: **1.18.0**
