### ISSUE TITLE
Indenting Compact Array of Mapping Breaks Yaml

### ISSUE THREAD

**Issue by cancan101** [redhat-developer/vscode-yaml#1128]
## Describe the bug

When selecting the yaml and indenting, the plugin produces broken yaml

## Expected Behavior

Code is properly indented.

## Current Behavior

Code is not properly indented and malformed.

## Steps to Reproduce

Using:
```yaml
children:
    - name: Items
      title: Items
```
Select text and hit tab.

Result:
```yaml
    children:
        - name: Items
        title: Items
```

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)
