### ISSUE TITLE
String "yes" is interpreted wrong

### ISSUE THREAD

**Issue by remcohaszing** [redhat-developer/vscode-yaml#116]
Given a Kubernetes MySQL deployment file:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
# ...
spec:
  # ...
  template:
    # ...
    spec:
      containers:
        - env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
          # ...
```

The value `yes` is a string. However, I am getting the following error in VSCode:

> Incorrect type. Expected "string".

Probably the string `"yes"` is incorrectly marked as a boolean.
