### ISSUE TITLE
Word completions on ctrl-space rather than completing possible keys

### ISSUE THREAD

**Issue by segevfiner** [redhat-developer/vscode-yaml#139]
I'm getting word completions on pressing ctrl-space, rather than getting completion for possible keys, which I believe would be more useful (They would show descriptions, keys that don't exist yet, etc.).

### Example
`.circleci/config.yml`:
```yaml
version: 2

jobs:
  build:
    docker:
      - image: python:3.7

    steps:
      - 
```
Try to trigger completion with ctrl-space on the dash after steps.

### Screenshot
![screenshot_2018-11-27_20-48-08](https://user-images.githubusercontent.com/24731903/49104599-0567de00-f287-11e8-8ef1-414450099e86.png)
