### ISSUE TITLE
support $schema convention in yaml file

### ISSUE THREAD

**Issue by sampaioletti** [redhat-developer/vscode-yaml#151]
Would it possible to support setting the schema within the yml file itself. Either as a top level declaration or as a comment?

i.e.

```yaml
$schema: http://json.schemastore.org/ansible-stable-2.5
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
...
```
or 
```yaml
# $schema: http://json.schemastore.org/ansible-stable-2.5
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
...
```
