### ISSUE TITLE
unknown tag <tag:yaml.org,2002:str>

### ISSUE THREAD

**Issue by EpicEric** [redhat-developer/vscode-yaml#173]
```yaml
"yes as a boolean": yes
"yes as a string": "yes"
"yes as a string with tag": !!str yes
```

The third line causes the error in the title of the issue. Is there currently no support for the [recommended schemas](https://yaml.org/spec/1.2/spec.html#Schema)? If there isn't, there should be at least some documentation on how to add this support locally.
