### ISSUE TITLE
[Feature Request] Auto formatting for list

### ISSUE THREAD

**Issue by joshuaavalon** [redhat-developer/vscode-yaml#179]
Assume `|` is the cursor.

Currently, when you press enter in the list
```yaml
list:
  - item|
```
It will add the indentation but not `-`
```yaml
list:
  - item
  |
```

I suggest that it should add `-` if you are in a list.

```yaml
list:
  - item
  - |
```

**Comment by fabstu** [comment]
I've got the same issue. It's pretty weird.

**Comment by fabstu** [comment]
Another testcase here. This one works correctly:

```yaml
- download:
  name: "Hello World"
  url: "value"
```

But this one does not.

```yaml
- download:
      name: "Hello World"
      url: "value"
```

The issue is that in one case download, url and name are in the same object and in the other download is the parent object which contains name and download. It moves name and url in the second on each format instead of keeping it the same/putting it at the correct indentation of a sub-item.
