### ISSUE TITLE
Custom tag not working for !!python/name

### ISSUE THREAD

**Issue by stevegroom** [redhat-developer/vscode-yaml#238]
I am using vscode for editing a project based around mkdocs. The mkdocs config file - mkdocs.yaml is always showing an error from the vscode yaml plug-in. 

I tried to set an exceptional format via the settings file but I can't get it to work. 

<img width="503" alt="customSettings" src="https://user-images.githubusercontent.com/2097486/67148580-34bd7a00-f2a1-11e9-8b45-999310af4143.png">

Is !!python/name supported as a custom tag?

regards
Steve

**Comment by JPinkney** [comment]
I'm not sure if I entirely understand custom tags for yaml but I've noticed that if you use one exclamation point (`!python/name` both in the custom tag and the yaml file) instead of two everything works correctly

I _think_ double exclamation point only works with the parser for tags listed [here](https://yaml.org/spec/1.2/spec.html#id2803231). I could be wrong though, I'm not intimately familiar with how https://github.com/mulesoft-labs/yaml-ast-parser works

**Comment by nurikk** [comment]
same problem here. came from java library called [snakeyaml](https://bitbucket.org/asomov/snakeyaml/wiki/Documentation)

yaml example:
```yaml
!!package.CarWithWheel
map: {id: 3}
part: !!org.yaml.snakeyaml.constructor.Wheel {id: 4}
plate: 12-XP-F4
wheel: {id: 2}
year: '2008'
```
