### ISSUE TITLE
.gitlab-ci.yml cache:key:files error

### ISSUE THREAD

**Issue by NatoBoram** [redhat-developer/vscode-yaml#252]
Looks like `.gitlab-ci.yml`'s [`cache:key:files`](https://docs.gitlab.com/ee/ci/yaml/#cachekeyfiles) is missing in the extension.

The following config : 

```yaml
cache:
  key:
    files:
      - package.json
      - yarn.lock
  paths:
    - node_modules
```

... gives me the following error : 

> Incorrect type. Expected "string".
