### ISSUE TITLE
YAML error markers off by one line 

### ISSUE THREAD

**Issue by chrmarti** [redhat-developer/vscode-yaml#254]
Issue Type: <b>Bug</b>

The backslashes need escaping, the error shows one line above:

```yaml
volumes:
  - "${PWD}/../..:${PWD}/../.."
command: "\([^ ]*\)"
```

![image](https://user-images.githubusercontent.com/9205389/70806998-dd2d1d80-1dbc-11ea-895f-b130802265f2.png)

VS Code version: Code - Insiders 1.41.0-insider (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-10T21:42:59.146Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.9.184-linuxkit
