### ISSUE TITLE
Validation Message: Property tags is not allowed.

### ISSUE THREAD

**Issue by tracker1** [redhat-developer/vscode-yaml#269]
I'm getting the following formatting squiggly in VS Code on the `tags` property in a Github workflow yaml file...

```
on:
  create:
    tags:
      - v*
```
