### ISSUE TITLE
Syntax error when accessing Jinja arrays

### ISSUE THREAD

**Issue by derdeagle** [redhat-developer/vscode-yaml#270]
When accessing Jinja arrays the syntax error "missed comma between flow collection entries
" is shown.

**Example code**
```
formula:
  config:
    foo: My value
    bar: {{ this_is_ok }}
    baz: {{ my_var['foobar'] }}
    key1: this is fine too
    key2: test
    key3: test
```
![Screenshot-2020-01-23](https://user-images.githubusercontent.com/11424540/72981367-e7d7cb00-3ddc-11ea-9b5f-595af6673388.png)

**Version**
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.12-200.fc31.x86_64
```
