### ISSUE TITLE
Duplicate keys reported on wrong lines (off-by-one)

### ISSUE THREAD

**Issue by DanTup** [redhat-developer/vscode-yaml#278]
When there are duplicate keys in my `pubspec.yaml`, the extension reports `duplicate key` on the wrong lines:

<img width="618" alt="Screenshot 2020-02-25 at 10 41 29" src="https://user-images.githubusercontent.com/1078012/75240028-99db2c00-57bb-11ea-9707-5ac5190c9d1f.png">

This is with [`pubspec.yaml` from `flutter_gallery`](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/pubspec.yaml) (with modifications to make dupes) on macOS, however it was reported to me by another user (with a different pubspec.yaml).

```yaml
name: flutter_gallery

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: any
  collection: 1.14.11
  device_info: 0.4.1+4
  intl: 0.16.1
  connectivity: 0.4.6+1
  string_scanner: 1.0.5
  scoped_model: 1.0.1 # this is the dupe
  url_launcher: 5.2.7
  cupertino_icons: 0.1.3
  video_player: 0.10.4+2
  scoped_model: 1.0.1 # this is the dupe
  shrine_images: 1.1.2
```
