### ISSUE TITLE
gitlab-ci.yml validation issues

### ISSUE THREAD

**Issue by rabidsloth** [redhat-developer/vscode-yaml#300]
This extension is throwing validation errors when using `allow_failure: true` within gitlab rules syntax. 
vscode-yaml version: 0.8.0

Example:
```
rules:
    - if: '$CI_COMMIT_REF_NAME != "master"'
      when: manual
      allow_failure: true
```
This is valid syntax as of Gitlab 12.8: https://docs.gitlab.com/ee/ci/yaml/#rulesallow_failure
