### ISSUE TITLE
"duplicate key" error

### ISSUE THREAD

**Issue by okachynskyy** [redhat-developer/vscode-yaml#301]
Version `0.7.2` and `0.8.0` displays `duplicate key` errors :

![image](https://user-images.githubusercontent.com/16646570/82659068-bbb84380-9c30-11ea-8abe-8a88e70c10f7.png)

Version 0.6.0 does not display these errors:

![image](https://user-images.githubusercontent.com/16646570/82658980-9a575780-9c30-11ea-8e6e-63c3df8b978d.png)

- yaml
```
version: '3.2'
services:
  db:
    container_name: test_postgress
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: test
      PGPASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    ports:
      - 5432:5432
```

-  VSCode: 
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 wk ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0
```

- macOS Catalina: `v10.15.1`
