### ISSUE TITLE
Invalid duplicate key error.

### ISSUE THREAD

**Issue by J-Siu** [redhat-developer/vscode-yaml#304]
YAML version: 0.8.0
vscode version: 1.45.1

```yml
version: "3"
services:
  jenkins:
    restart: unless-stopped
    logging:
      options:
        tag: "{{.Name}}"
    image: ${MY_JENKINS_IMG}
    container_name: ${MY_JENKINS_NAME}
    expose:
      - ${MY_JENKINS_HTTP}
      - ${MY_JENKINS_SLAV}
    volumes:
      - ${TZ_FILE}:${TZ_FILE}:ro
      - ${MY_JENKINS_DAT}:/var/jenkins_home
    restart: always
```

Above yml gives following error in "PROBLEM" tab:

```json
{
	"resource": "/data/home/js/compose.vms01/test.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "duplicate key",
	"startLineNumber": 3,
	"startColumn": 42,
	"endLineNumber": 3,
	"endColumn": 42
}
{
	"resource": "/data/home/js/compose.vms01/test.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "duplicate key",
	"startLineNumber": 15,
	"startColumn": 347,
	"endLineNumber": 15,
	"endColumn": 347
}
```
