### ISSUE TITLE
Required attributes are inserted with wrong level of indentation on first array item

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-yaml#312]
- use https://gist.github.com/lburgazzoli/4a74731d494ef6060e557402697b89cd#file-camel-yaml-dsl-schema-latest-json-L2852-L2872
- modify yaml.schemas to use it
- type `- `
- call completion
- choose `from`
--> it creates:
```
- from:
  steps:
    - 
  uri: 
```
although it should be:
```
- from:
    steps:
      - 
    uri: 
```
