### ISSUE TITLE
Weird "problems" in YAML file at certain location

### ISSUE THREAD

**Issue by theAkito** [redhat-developer/vscode-yaml#320]
```yaml
{{- if .Values.ingressroutetcp.enabled -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutetcps.traefik.containo.us

spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRouteTCP
    plural: ingressroutetcps
    singular: ingressroutetcp
  scope: Namespaced
{{- end -}}
```

This is a CRD I use in a Helm Chart.

It is valid YAML and confirmed to work. When it is in the _templates_ directory, it is fine and accepted. When the precisely same file is moved to the _crds_ directory, I get lots of "problems" showing up. Removing the if condition for the file removes the "problems".

![](https://i.imgur.com/RcP5KsX.png)

Looking at the errors, please do not forget: all these errors are gone, when the file is moved to a different directory. So these errors cannot be related to a faulty YAML, per sé.

Now, I don't know if this is related to the Kubernetes extension that apparently depends on this YAML extension, as presumingly, this particular extension should not care, at all, where the YAML to be linted is located. However, I am not sure where to start with this issue, so I decided to start here.
