### ISSUE TITLE
Missing property "key_value" with Ansible Set_Fact

### ISSUE THREAD

**Issue by PhilThurston** [redhat-developer/vscode-yaml#340]
Right now while using ansible for example you will get an error of MIssing Property "key_value" when using any format of the set_fact module in yaml. You can reproduce this by taking any example from https://docs.ansible.com/ansible/latest/modules/set_fact_module.html for example:

```
- set_fact:
    one_fact: something
    other_fact: "{{ local_var * 2 }}"
    cacheable: yes
```

it shouldn't be
