### ISSUE TITLE
Request textDocument/documentSymbol when there is both a --- and a comment

### ISSUE THREAD

**Issue by rgarrigue** [redhat-developer/vscode-yaml#355]
Hi there

Working on ansible, I keep having these

```
[Error - 08:30:58] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'lineComments' of undefined
  Code: -32603 
``` 

It happens editing anything in

```yaml
---
# tasks file for ansible-role-consul-template

- name: Install ansible unarchive requirement
  package:
    name: tar
```

Playing with it, it doesn't like having both `---` and the comment. Remove one of those and it's happy.

I guess it's not specific to Ansible, but the role skeleton from ansible-galaxy comes with a bunch of file like this, ` --- \n # xxx file for whatever-role`
