### ISSUE TITLE
String does not match the pattern of "^PowerShell@2$".

### ISSUE THREAD

**Issue by sheeeng** [redhat-developer/vscode-yaml#356]
We have the following task in `azure-pipelines.yaml` file.

```yaml
    - task: PublishBuildArtifacts@1
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      displayName: 'Publish Build Artifacts'
```

The below false positive error will be shown on the `PublishBuildArtifacts@1` line.

```text
Publish build artifacts to Azure Pipelines or a Windows file share
String does not match the pattern of "^PowerShell@2$".
Peek Problem (Alt+F8)
No quick fixes available
```

See [related issue](https://github.com/microsoft/vscode/issues/100476).

**Comment by JPinkney** [comment]
Related schema on schema store: https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json. Looks like something might be getting messed up with the anyOf. Can you paste the erroring yaml so that we can try it out and test

**Comment by sheeeng** [comment]
The entire reproducible file are listed below.

```yaml
---
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'BuildStage'
  jobs:
  - job: 'BuildJob'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PublishBuildArtifacts@1
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      displayName: 'Publish Build Artifacts'
      inputs:
        pathToPublish: artifacts
        artifactName: artifacts
```

**Comment by iBrooks** [comment]
I also have this issue. 

Code:
`steps:
        - task: ArchiveFiles@2
          displayName: package functionapp
          inputs:
            rootFolderOrFile: $(System.DefaultWorkingDirectory)/email-endpoint/functionapp
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            replaceExisitingArchive: true`

Screenshot of error:
![image](https://user-images.githubusercontent.com/7727330/95346664-18d42f00-088a-11eb-805c-0824e96ff117.png)

**Comment by evidolob** [comment]
@JPinkney @gorkem 
I done investigation around this issue, the problem in schema itself, it is used `ignoreCase` field for some object fields. I cannot find any mentions of `ignoreCase` in JSON Schema spec, across schema it has different values, like `key`, `all`, `value`. 
json-language-server also doesn't have support of this:
<img width="1045" alt="Screenshot 2020-10-26 at 11 31 39" src="https://user-images.githubusercontent.com/929743/97156728-c5b21580-177f-11eb-828a-3ab255a6ebd9.png">

Schema used for that JSON is  https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json 
As you can see it has exactly the same error.

And error happened because object with `PublishBuildArtifacts@1` defined as:
```json
        {
          "properties": {
            "task": {
              "description": "Publish build artifacts\n\nPublish build artifacts to Azure Pipelines or a Windows file share",
              "ignoreCase": "value",
              "pattern": "^PublishBuildArtifacts@1$"
            },
            "inputs": {
              "description": "Publish build artifacts inputs",
              "properties": {
                "PathtoPublish": {
                  "type": "string",
                  "description": "Path to publish",
                  "ignoreCase": "key"
                },
                "ArtifactName": {
                  "type": "string",
                  "description": "Artifact name",
                  "ignoreCase": "key"
                },
...
              "additionalProperties": false,
              "required": []
            }
          },
          "firstProperty": [
            "task"
          ],
          "required": [
            "task"
          ]
        }
```
So next yaml doesn't have error:
```yaml
---
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'BuildStage'
  jobs:
  - job: 'BuildJob'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PublishBuildArtifacts@1
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: artifacts
        ArtifactName: artifacts
```

Need to set `pathToPublish` -> `PathtoPublish` and `artifactName` -> `ArtifactName` as their names defined in schema.

In the end, I not sure that we need to implement support of `ignoreCase`, as it is not part of JSON Schema specification.
WDYT?
