### ISSUE TITLE
When the file name is:"prometheus.yml",Syntax cannot be displayed correctly

### ISSUE THREAD

**Issue by is-a-gamer** [redhat-developer/vscode-yaml#369]
Error Info "Incorrect type. Expected one of object, null."

**Comment by evidolob** [comment]
Hi, @is-a-gamer can you add yaml content where you get that error?

**Comment by is-a-gamer** [comment]
```yaml
- name: initing variables
  stat:
    path: "{{ service_install_dir }}"
  register: p
```
Something like this 

> 嗨，@ is-a-gamer可以在出现错误的地方添加yaml内容吗？
