### ISSUE TITLE
CircleCI schemastore one-of selector does not work

### ISSUE THREAD

**Issue by miqm** [redhat-developer/vscode-yaml#370]
In Circleci config v.2.1, in executors there's several types to be chosen: docker, machine, macos, windows. 

In schemastore JSON schema for circleci I can see that they are provided in "oneOf" array, however this does not work:

![image](https://user-images.githubusercontent.com/7921224/94520080-f27c1700-022b-11eb-9ada-533800eae2cc.png)

Could this be checked? I'm not sure if this this a problem of the plugin interpreting schema or the schema itself.

**Comment by JPinkney** [comment]
This is actually an interesting issue. It looks like what's happening is machine actually requires image underneath it. It also looks like resource_class shouldn't be under machine_executor (according to the schema) because thats part of the dockerExecutor part of the schema. So what's happening is because machine doesn't validate correctly it's actually trying to validate against the dockerExecutor in the schema instead.

With this YAML
```yaml
version: 2.1
executors:
  machine_executor:
    machine:
      docker_layer_caching: true
```
we get `Missing property "image".` which is the correct error 

then when we add resource_class
```yaml
version: 2.1
executors:
  machine_executor:
    machine:
      docker_layer_caching: true
    resource_class: medium
```

we get the `missing property docker` error because it's trying to match against the dockerExecutor instead of the machineExecutor, since resource_class is in the oneOf of dockerExecutor.

In this case everything is actually behaving as expected
