### ISSUE TITLE
incorrect error with regex in ansible

### ISSUE THREAD

**Issue by waterponey** [redhat-developer/vscode-yaml#372]
Hi,

I'm using vscode and this extension (version 0.11.1) and I'm using it on a project using ansible yaml files.

Some configuration are supposed to get regex strings as values (for instance insertafter from [lineinfile ](https://docs.ansible.com/ansible/2.5/modules/lineinfile_module.html) ) and I get an error there 
![image](https://user-images.githubusercontent.com/5795546/94948364-7e699980-04df-11eb-82ab-f51d556eea9b.png)

I'm not sure how to remove these

**Comment by evidolob** [comment]
@waterponey Hi,
Can you share example of your yaml file?

**Comment by waterponey** [comment]
Hi, this snippet is raising the error I mentionned.

```
- name: Ensure admin group has sudo rights
  lineinfile:
    path: /etc/sudoers
    state: present
    line: '%admin       ALL=(ALL) '
    insertafter: '^# %wheel'
    validate: 'visudo -cf %s'
```
