### ISSUE TITLE
Auto-completion on sub-objects doesn't work

### ISSUE THREAD

**Issue by schickling** [redhat-developer/vscode-yaml#38]
First of all: Thanks a lot for your awesome progress on this plugin today!

I've just tried it and it seems to work well on the root level. However, auto-completion doesn't seem to work on a sub-level. Here is an example:

```yaml
# auto-complete works for `my_field`
my_root_field: 42

my_other_root_field:
  some_dynamic_key: # this key can be chosen arbitrarily
    sub_field: 0 # this again is a concrete, pre-defined key: auto-completion doesn't work
```
