### ISSUE TITLE
Ansible apply tags: Incorrect type

### ISSUE THREAD

**Issue by Mystic8b** [redhat-developer/vscode-yaml#383]
## Describe the bug

An error is highlighted when using apply: tags

## Expected Behavior

Error not found

## Current Behavior

Found error

## Steps to Reproduce

1. Create a playbook for ansible;
2. Apply tag to a task that includes a role.

For example:
```
  - name: Configure Iptables
    include_role:
      name: conf_iptables
      apply:
        tags: iptables
    tags: iptables
```
![image](https://user-images.githubusercontent.com/35394377/97103608-96879f80-16be-11eb-97bb-ef0617d11c3b.png)

## Environment
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)
