### ISSUE TITLE
Let the file specify schema (url)

### ISSUE THREAD

**Issue by RobberPhex** [redhat-developer/vscode-yaml#389]
Is there any possibility to let the file specify schema?

When editing the YAML file, the author knows exactly which schema should be applied. So there could be a header or something to specify the schema.

For example:
```yaml
"http://json-schema.org/schema#":
  - https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json
  - https://kubernetesjsonschema.dev/v1.10.3-standalone/service-v1.json
--
apiVersion: v1
kind: Service
......
```

1. This brings the out-of-box validation, auto-completion for the editor. The file is autonomous.
2. It could be possible to build a general validation service.
3. The choice of schema could be more precise. choosing by filename pattern isn't precise in some situations.
4. For some schema extension, It could be easier to help user write YAML. Such as CustomResourceDefinitions in kubernates.

The example is not ideal. But this VSCode extension could support this non-stranded way. In the future, we can help users immigrate.

Related issue:
https://github.com/json-schema-org/json-schema-spec/issues/828#issuecomment-572626261
