### ISSUE TITLE
Doesn't recognize yaml syntax for regular expressions as valid.

### ISSUE THREAD

**Issue by vtcifer** [redhat-developer/vscode-yaml#392]
## Describe the bug
[Valid YAML syntax for regular expressions ](https://yaml.org/YAML_for_ruby.html#regexps) reported as invalid (unknown tag)

## Expected Behavior
Entries should not display an error.

## Current Behavior
Entries are flagged as unknown tag

## Steps to Reproduce

1. Create a file and ensure language is set to YAML.
2. Use the following yaml:
```yaml
---

case-insensitive: !ruby/regexp "/George McFly/i" 
complex: !ruby/regexp "/\\A\"((?:[^\"]|\\\")+)\"/" 
simple: !ruby/regexp '/a.b/' 
```
3. Observe error listed under text `!ruby/regexp`  -> Invalid Tag: <!ruby/regexp>

## Environment
- [X] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)
