### ISSUE TITLE
Incorrect behaviour when working with helm templates

### ISSUE THREAD

**Issue by Jasstkn** [redhat-developer/vscode-yaml#407]
## Describe the bug
When work with helm templates, there are a lot of wrong errors.

## Expected Behavior
Should work correctly as it was before

## Current Behavior
Mark a lot of lines as containing error

## Steps to Reproduce
1. Open any helm template file
2. See a lot of errors which are wrong

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

<img width="360" alt="Screenshot 2020-12-11 at 19 53 02" src="https://user-images.githubusercontent.com/20466436/101931456-808c5a80-3bea-11eb-8ec7-c3096fd48ccf.png">

**Comment by JPinkney** [comment]
Do you have any other kubernetes related extensions installed? Also, what file type is your file associated with? (You can see that this file is associated with the YAML filetype in the bottom right. 

![2020-12-11-122052_960x1010_scrot](https://user-images.githubusercontent.com/8839537/101934063-0ee0ec00-3bab-11eb-8efa-541babb905bf.png)

**Comment by Jasstkn** [comment]
@JPinkney, yeah, I have several extensionsm but when I disable only this one, no red lines appeared
<img width="374" alt="Screenshot 2020-12-12 at 00 45 37" src="https://user-images.githubusercontent.com/20466436/101957892-5c913f00-3c13-11eb-8cc7-211fc5e2378b.png">

**Comment by JPinkney** [comment]
Are you able to post more of your yaml file? Do you have another apiVersion at the root of the document?

**Comment by sagor999** [comment]
I have same problem. 
Here is an example yaml file:
```
{{- if .Values.hooks.enabled -}}
apiVersion: batch/v1
 kind: Job
metadata:
  name: {{ template "sentry.fullname" . }}-db-init
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "{{ if .Values.hooks.removeOnSuccess }}hook-succeeded,{{ end }}before-hook-creation"
    "helm.sh/hook-weight": "6"
spec:
  template:
    metadata:
      name: {{ template "sentry.fullname" . }}-db-init
      annotations:
        checksum/configmap.yaml: {{ include (print $.Template.BasePath "/configmap-sentry.yaml") . | sha256sum }}
        {{- if .Values.sentry.worker.annotations }}
{{ toYaml .Values.sentry.worker.annotations | indent 8 }}
        {{- end }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
        {{- if .Values.sentry.worker.podLabels }}
{{ toYaml .Values.sentry.worker.podLabels | indent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- if .Values.images.sentry.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.sentry.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: db-init-job
        image: "{{ template "sentry.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.sentry.pullPolicy }}
        command: ["sentry","upgrade","--noinput"]
        env:
        {{- if .Values.postgresql.enabled }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ default (include "sentry.postgresql.fullname" .) .Values.postgresql.existingSecret }}
              key: {{ default "postgresql-password" .Values.postgresql.existingSecretKey }}
        {{- end }}
        {{- if .Values.hooks.dbInit.env }}
{{ toYaml .Values.hooks.dbInit.env | indent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        resources:
{{ toYaml .Values.hooks.dbInit.resources | indent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-sentry
{{- end -}}
```
And this is how it looks with YAML extension currently:
![Screenshot from 2020-12-18 07-12-57](https://user-images.githubusercontent.com/18602811/102629794-7ee9f780-4100-11eb-8ab2-9d55947f553c.png)

It gets tripped on the first `{{` and after that the rest of the file is messed up.

**Comment by sagor999** [comment]
Found workaround to this issue.
I installed Kubernetes extension to vscode, and it automatically marked helm files as helm-template type, and it is no longer being attempted to be validated by YAML extension. So problem went away. :)

**Comment by JPinkney** [comment]
If you are using helm you should definitely install vscode-kubernetes! It interfaces with this extension in order to provide its support. The reason why your helm yaml doesn't validate correctly is because something like:
```yaml
{{- if .Values.hooks.enabled -}}
apiVersion: batch/v1
 kind: Job
metadata:
  name: {{ template "sentry.fullname" . }}-db-init
{{- end -}}
```
isn't valid in yaml 1.2. It's only valid in helms custom yaml
