### ISSUE TITLE
Not able to collapse YAML map if value of last key is sequence

### ISSUE THREAD

**Issue by GreenSmile** [redhat-developer/vscode-yaml#422]
## Describe the bug
Example of broken YAML code:
```
top1:
  second11:
    name: one
    events:
      - element
  second12:
    name: two
```

**Issue:** 
Trying to collapse map "second11" results in the following:
![image](https://user-images.githubusercontent.com/4628718/106530740-44c39200-64c3-11eb-9309-b0908d15e14c.png)

## Expected Behavior
Collapse works fine if sequence is not the last value of the map.

Example of working YAML code:
```
top1:
  second11:
    events:
      - element
    name: one
  second12:
    name: two
```

Trying to collapse map "second11" result in the following:
![image](https://user-images.githubusercontent.com/4628718/106530858-79cfe480-64c3-11eb-841d-f0725ab5ddb9.png)

## Environment
- [x] Mac

Issue affects YAML extension 0.14.0
Is **not** reproducible if YAML extension is disabled
Is **not** reproducible in 0.13.0
