### ISSUE TITLE
Kubernetes v1.19 not supported

### ISSUE THREAD

**Issue by maltalex** [redhat-developer/vscode-yaml#424]
I'm opening this issue here because of the plugin's claim to have "built-in Kubernetes syntax support".

Unfortunately, it looks like the K8s stops at 1.18 and there's no support for 1.19+

## Expected Behavior
Schema support for Kubernetes v1.19+

## Current Behavior
Kubernetes yaml v1.19+ not supported. The plugin uses older schema definitions and does not recognize new fields.

## Steps to Reproduce
Copy the following yaml into vscode, select "kubernetes" as the schema. Several properties including "pathType", and "backend" will not be allowed:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: test
            port:
              number: 80
```

![image](https://user-images.githubusercontent.com/10195391/107153168-b3499980-6974-11eb-85ca-c6984bef979e.png)

for reference, my schema definition file:

```
{
    "yaml.schemas": {
        "kubernetes": ["*.yaml"]
    }
}
```

## Environment
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)
