### ISSUE TITLE
YAML Anchors and References Break Schema Validation and Suggestions

### ISSUE THREAD

**Issue by svrx** [redhat-developer/vscode-yaml#425]
## Describe the bug
When user anchors or references in CloudFormation YAML files, schemas stops working when anchors/references are used.

## Expected Behavior
It works as normal.

## Current Behavior
Following error keeps repeating as elements are hovered.
```
Error thrown while requesting schema "Error: end of the stream or a document separator is expected" when calling the registered contributor "cloudformation"
```

## Steps to Reproduce

1. Add an anchor to any element
``` yaml
...
 Tags: &tags
   - Key: Application
     Value: MyApp
...
```
## Environment
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by evidolob** [comment]
@svrx Can you share more info on this? 
I cannot reproduce this:
<img width="526" alt="Screenshot 2021-02-24 at 14 53 38" src="https://user-images.githubusercontent.com/929743/109003517-388cb800-76b0-11eb-808f-79629e2bf3ca.png">

Do you use only `vscode-yaml` ? Or some other extension which depends on it?

**Comment by svrx** [comment]
Thanks for investigating. 
I've investigated the issue further on my setup and have been able to narrow down to some interaction with `kddejong.vscode-cfn-lint`.
Will bring to maintainers awareness.
Is there anything you can check on your side?

**Comment by evidolob** [comment]
It would be nice, if you can share yaml, on which you got validation broken, to let me check more deeply.

**Comment by svrx** [comment]
Something as simple as this is enough.
``` yaml
AWSTemplateFormatVersion: '2010-09-09' 
Resources:
  ServiceCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ClusterName
      Tags: &tags
        - Key: Application
          Value: AppName
        - Key: ApplicationRole
          Value: FrontEnd
  WebLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: LBName
      Type: application
      Tags: *tags
```

As soon as the anchor (&tags) is added, following error start appearing anytime an element is hovered.
![image](https://user-images.githubusercontent.com/713996/109982862-36eb7180-7cfa-11eb-99c9-0d1487f2f857.png)
