### ISSUE TITLE
array/object completion: do not auto-generate properties with default values

### ISSUE THREAD

**Issue by fbaligand** [redhat-developer/vscode-yaml#429]
### Is your enhancement related to a problem? Please describe.
Currently, when I use auto-completion for an "array" or "object" property, all sub-properties with a default value are automatically generated.
This is a problem because:
- as a user, I don't especially want to customize all sub-properties with default values. And so, I want to choose each one I want to customize
- For JSON files, VSCODE itself has not this behavior: it generates no sub-properties
- when you have nearly all your properties with default values, it generates a bunch of properties.

### Describe the solution you would like
Instead of generating all sub-properties with default values, I would like either:
- no sub-properties generated at all
- or only "required" sub-properties
- or first defaultSnippet found (or the one named "default")

### Additional context
One example, with this [json schema](https://github.com/fbaligand/vscode-logstash-editor/blob/master/yamlschemas/pipelines.yml.schema.json) :
- Say I have an empty `pipelines.yml` file
- I type `-` and use `(array item)` completion
- generated snippet is:
``` yaml
- pipeline.id: 
  pipeline.java_execution: true
  pipeline.ordered: auto
  path.config: 
  config.string: 
  config.debug: false
  config.support_escapes: false
  config.reload.automatic: false
  config.reload.interval: 3s
  pipeline.workers: 
  pipeline.batch.size: 125
  pipeline.batch.delay: 50
  pipeline.plugin_classloaders: false
  queue.type: memory
  queue.page_capacity: 64mb
  queue.max_events: 0
  queue.max_bytes: 1024mb
  queue.checkpoint.acks: 1024
  queue.checkpoint.interval: 1000
  queue.checkpoint.writes: 1024
  queue.checkpoint.retry: false
  queue.drain: false
  path.queue: "<path.data>/queue"
  dead_letter_queue.enable: true
  dead_letter_queue.max_bytes: 1024mb
  path.dead_letter_queue: 
```
