### ISSUE TITLE
Support for multiple YAML documents in single file

### ISSUE THREAD

**Issue by ahmetb** [redhat-developer/vscode-yaml#43]
Some of my Kubernetes yaml files are in form of:

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
...
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userdirectory-deployment
...
```

it looks like the autocomplete/<kbd>Ctrl</kbd>+<kbd>space</kbd> is not working when there are multiple objects in a single yaml file. 

Should this be supported?
