### ISSUE TITLE
yml formatting error cause invalid yml file

### ISSUE THREAD

**Issue by robertlugg** [redhat-developer/vscode-yaml#449]
## Describe the bug
Formatting of this yaml file doesn't yield valid yaml; comment confusion

! Please note:  I don't know that my input is strictly yaml syntax, but Python yaml does read it correctly.

``` python
import yaml
with open("yml_format_bug.yml") as fp:
    yaml.safe_load(fp)
```

### input yaml

```yaml
first: 123

v1: {
    file: PYTHON_TO_RUN_REMOTELY, 
    type:   env # A type of 'env' pulls the value from an environment variable.
            # Only works for file: and path: values., absolute: true
}

v2:
    file: PYTHON_TO_RUN_REMOTELY
    type:   env # A type of 'env' pulls the value from an environment variable.
            # Only works for file: and path: values., absolute: true

last: 123
```

## Expected Behavior
I don't know what the correct format should be, but it should give valid yaml in any case.  Here is an example of what it might look like.  I don't particularly care the format

``` yaml
first: 123

v1: { file: PYTHON_TO_RUN_REMOTELY, type: env # A type of 'env' pulls the value from an environment variable.
      # Only works for file: and path: values., absolute: true 
}

v2:
  file: PYTHON_TO_RUN_REMOTELY
  type:
    env # A type of 'env' pulls the value from an environment variable.
    # Only works for file: and path: values., absolute: true

last: 123

```

## Current Behavior
Closing curly gets put into comment causing yaml to be invalid.

``` yaml
first: 123

v1: { file: PYTHON_TO_RUN_REMOTELY, type:
      env # A type of 'env' pulls the value from an environment variable.
      # Only works for file: and path: values., absolute: true }

v2:
  file: PYTHON_TO_RUN_REMOTELY
  type:
    env # A type of 'env' pulls the value from an environment variable.
    # Only works for file: and path: values., absolute: true

last: 123
```

## Steps to Reproduce
Create new file containing my "Input yaml" above.
Change file type to yaml if necessary.
Press <ctrl><shift>I in vscode with extension installed and enabled.

## Environment
- [ ] Windows
- [ ] Mac
- [ X ] Linux
- [ ] other (please specify)
