### ISSUE TITLE
Peculiar behavior around anchors and comments

### ISSUE THREAD

**Issue by max-sixty** [redhat-developer/vscode-yaml#459]
## Expected Behavior
I have this yaml:

```yaml
when: &shall
  # we three meet again; in lightning, thunder and in
  rain:
```

## Current Behavior

It moves the comment to the anchor:

```yaml
when: &shall # we three meet again; in lightning, thunder and in
  rain:
```

## Expected Behavior 2

It's even worse if the comment is long:

```yaml
when: &shall
  # we three meet again; in lightning, thunder and in lightning, thunder and
  rain:
```

## Current Behavior 2

It moves the anchor down to the next line

```yaml
when:
  &shall # we three meet again; in lightning, thunder and in lightning, thunder and
  rain:
```

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)
