### ISSUE TITLE
Several errors on valid GitHub action yml

### ISSUE THREAD

**Issue by alvinseville7cf** [redhat-developer/vscode-yaml#492]
## Summary
Several errors on valid GitHub action .yml are shown in the following Visual Studio Code version:
```
Version: 1.55.0 (system setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```
## Description
I have the [following](https://github.com/alvinseville7cf/Program-Generator/blob/ci/.github/workflows/ci.yml) valid GitHub Action .yml:
```yml
name: CI

on:
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: sample
      run: echo "Is not implemented yet."

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: sample
      run: echo "Is not implemented yet."
```
I also have .yml linter configured as:
```yml
    "yaml.schemas": {
        "https://json.schemastore.org/github-action.json": "*.yml"
    },
```
But unexpectedly it shows me several errors:
![image](https://user-images.githubusercontent.com/42812113/115641522-9e1dbd80-a35c-11eb-8200-6b55e3e8a578.png)

How to fix it? What am I missing?
