### ISSUE TITLE
Extracting xpath to specific line 

### ISSUE THREAD

**Issue by spark706** [redhat-developer/vscode-yaml#527]
## Summary
Is there a method to extract the xpath for any given line within a yaml file?  

For example

```
top:
  first:
    - name: myname
      attr1: val1
      attr2: val2
    - value2
    - value3
  second:
    child1: value1
    child1: value2
    child3: value3
```

Suppose I would like to see what the xpath is for `val2` which is `top.first.attr2`.

There may be something in the yaml extension and just missing it or someone may know a simple way but figured I would ask.
