### ISSUE TITLE
Validation does not work with kubernetes yaml

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-yaml#54]
Settings:
```json
{
    "yaml.schemas": {
        "kubernetes": "pod.yaml"
    }
}
```
pod.yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: azure-vote-back
specs:
  containers:
  - name: azure-vote-back
    image: redis
    imagePullPolicy: Always
    ports:
    - containerPort: 6379
      name: redis
```
Result:
![image](https://user-images.githubusercontent.com/16755094/34972606-8c9a12b6-fabd-11e7-97f3-f06241f22ca9.png)

Expected result:
![image](https://user-images.githubusercontent.com/16755094/34972615-97885bc4-fabd-11e7-90c8-dd3f0748f52f.png)
