### ISSUE TITLE
Auto-completion does not work with Kubernetes YAML files

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-yaml#55]
Settings:
```json
{
    "yaml.schemas": {
        "kubernetes": "pod.yaml"
    }
}
```
pod.yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: azure-vote-back
spec:
  containers:
  - name: azure-vote-back
    image: redis
    imagePullPolicy: Always
    ports:
    - containerPort: 6379
      name: redis
```
Result:
![image](https://user-images.githubusercontent.com/16755094/34972669-01bb6c84-fabe-11e7-8c4e-faefd0575a93.png)

Expected result:
![image](https://user-images.githubusercontent.com/16755094/34972677-15527a76-fabe-11e7-953d-b82f13db4689.png)
