### ISSUE TITLE
Unable to load remote schema with http protocol

### ISSUE THREAD

**Issue by Graham42** [redhat-developer/vscode-yaml#550]
## Describe the bug

The latest version, `0.21.0` introduced a bug if a yaml file uses 
```yaml
# yaml-language-server: $schema=http://json-schema.org/draft-07/schema#
```
An error is shown
> Unable to load schema from '**/project/root/dir**/http:/json-schema.org/draft-07/schema#': .YAML(768)

## Expected Behavior

The remote schema should be loaded

## Current Behavior

An error is reported

## Steps to Reproduce

1. Upgrade to `0.21.0`
2. Create a yaml file with the contents
    ```yaml
    # yaml-language-server: $schema=http://json-schema.org/draft-07/schema#

    properties:
      foo:
        type: string
    ```

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

## Workaround

1. In the Extensions tab, find the YAML plugin
2. Open the menu for the plugin (Gear Icon)
3. Choose 'Install Another Version'
4. Install version `0.20.0`
