### ISSUE TITLE
Schema URL fragments broken since 0.21.0

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [redhat-developer/vscode-yaml#557]
## Describe the bug
Given a yaml file with something like this as the first line:
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json#/definitions/Schema
```
In 0.20.x and before, the sub-schema was correctly loaded and applied to the document.

In 0.21.0, the remote load is broken, and in 0.21.1, it ignores the fragment and applies the top level schema.

## Expected Behavior
It should obey the URL fragment like it used to, so that portions of schemas can be used. This is especially important for validating the targets of `$ref` properties from OpenAPI schemas.

## Current Behavior
It ignores the fragment and validates the file using the "root" schema, which produces bazillions of bogus schema validation errors.

## Steps to Reproduce
1. Create a file using the fragment reference, which should validate according to the fragment. For example:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json#/definitions/Schema
type: string
pattern: ^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$
```
2. It should validate correctly
3. Instead it complains that properties for a top level OpenAPI document are missing

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)
