### ISSUE TITLE
Yaml Validation on Standalone Network on Windows not working

### ISSUE THREAD

**Issue by JakeHadley** [redhat-developer/vscode-yaml#571]
Hi, my team is trying to do a proof-of-concept utilizing yaml files and schemas. We're working on a standalone network and recently had this extension made available to us. Our project is not anything to do with CI/CD, but we are just looking to do standard validation on yaml files. I'm a little confused on what is needed to make this extension work correctly. For simplicity's sake, let's say my project structure is super simple:

```
demo/
    type1/
        file1.yaml
        file2.yaml
    type2/
        file3.yaml
        file4.yaml
    schemas/
        schema.yaml
```
I just have a few files/folders and want to validate them using my yaml schema `schema.yaml`. 

I've installed the extension, established in `yaml.schemas` what I think it should be:
```json
"yaml.schemas": {
     ".\\schemas\\schema.yaml": ["*.yaml"]
}
```
And when I go to my yaml file, no errors appear, nor do any suggestions. My yaml file looks like
```yaml
---
property1 : "banana"
property2: 2
property3: "java"
property4: 
    - #creating some stuffs with this here comment
        - type: "test"
          name: "validation"
          num_items: 15
        - type: "real"
          name: "release"
          num_items: 10
```

While the schema looks like 
```yaml
type: object
properties: 
    property1:
        type: string
        enum: ["banana", "apple", "orange"]
    property2:
        type: integer
    property3: 
        type: string
    property4: 
        type: array
        items: 
            type: object
            properties: 
                 type: 
                     type: string
                 name:
                     type: string
                 num_items:
                     type: integer
                     minimum: 0
                     maximum: 15
```
Is there something that I'm missing? Does the language server have to be started somehow? I'm honestly not sure how the yaml file should be fashioned, and I've had a hard time finding out what valid yaml is supposed to look like. Any help would be appreciated.
