### ISSUE TITLE
The plugin does not recognize !!binary

### ISSUE THREAD

**Issue by symbiont-val-melamed** [redhat-developer/vscode-yaml#580]
## Describe the bug
It seems that the plugin does not support [binary data](https://yaml.org/type/binary.html). I get a message in the editor:

> unknown tag <tag:yaml.org,2002:binary>

## Expected Behavior
The tag should be recognized and no error message should be displayed.

## Current Behavior
Displays:

> unknown tag <tag:yaml.org,2002:binary>

## Steps to Reproduce
Enter:

```yaml
---
test:
  key: !!binary "MDEyMzQ1Njc4OWFiY2RlZkFCQ0RFRg=="
```

## Environment
- [x] Windows (WSL)
