### ISSUE TITLE
Support for anchors/references?

### ISSUE THREAD

**Issue by rylnd** [redhat-developer/vscode-yaml#60]
Hi! First, thanks for the great plugin.

I'm having an issue with validations not respecting injected references. For example, in a Circle CI 2.0 config file, I've got the `docker` key in a reference:

```yaml
defaults: &job_defaults
  docker:
    - image: circleci/node:8.2.1
```
and then use it later in a job:
```yaml
jobs:
  job1: 
    <<: *job_defaults
```
However, I still receive a `Missing property "docker".` message on the `job1` node.

Is this the expected behavior? Thanks in advance.
