### ISSUE TITLE
unknow tag opencv-matrix

### ISSUE THREAD

**Issue by MakerFace** [redhat-developer/vscode-yaml#611]
## Summary
unknown tag <tag:yaml.org, 2002:opencv-matrix> YAML

## Relevant information
```yaml
%YAML:1.0
   ---
   cali: "123"
   ca_matrix: !!opencv-matrix
      rows: 3
```
