### ISSUE TITLE
IntelliSense broken with v1.0.0

### ISSUE THREAD

**Issue by mdschweda** [redhat-developer/vscode-yaml#616]
## Describe the bug

https://user-images.githubusercontent.com/3602273/137896444-e1457b7a-31af-46ec-b19c-cc8bb86c8e55.mp4

```jsonc
// .vscode/settings.json
{
  "yaml.schemas": {
    "Kubernetes": "*.yaml"
  }
}
```

```yaml
# test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: test
      image: alpine
```

See video above:

- IntelliSense for `spec.containers[]` should suggest `workingDir`
- `{} - (array item)` is unexpected
- After adding `spec.volumes`, IntelliSense incorrectly lists suggestions for `spec.volumes[]` instead of `spec.containers[]`

The error does not occur after switching back to version 0.23.0.

## Environment
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)
