### ISSUE TITLE
">>"should't recognized be a map keys.

### ISSUE THREAD

**Issue by IceTiki** [redhat-developer/vscode-yaml#627]
## Describe the bug

"<<" recognized be a map key. And throw an error "Map keys must be unique. "

There is an example. 

![image](https://user-images.githubusercontent.com/61530581/139357587-a05b179c-5582-42d6-aa4b-ce3b55210b22.png)

![image](https://user-images.githubusercontent.com/61530581/139357618-a3c46614-b20a-4e93-af0b-eb23182e9e62.png)

```yaml
a: &asdasd
  b: 1
  c: 2

b: &qweqwe
  g: 5
  h: 6

x:
  as: 123
  <<: *asdasd
  <<: *qweqwe
```

## Expected Behavior

...

## Current Behavior

...

## Steps to Reproduce

...

## Environment

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by adamday2** [comment]
Note, this bug is not present in 0.23

**Comment by evidolob** [comment]
This extension from `1.0.0` use YAML `1.2` version by default, YAML has dropped `<<` in `1.2`. So from validator point of view `<<` is regular key.
To change that behaviour you need to switch to `1.1` yaml version, you can do that with adding
```yaml
%YAML 1.1
---
``` 
on top of your file or change it in user preference `yaml.yamlVersion` to `1.1`

**Comment by so-jelly** [comment]
Alternatively, use the yaml 1.2 syntax:

```
a: &asdasd
  b: 1
  c: 2

b: &qweqwe
  g: 5
  h: 6

x:
  as: 123
  <<: [ *asdasd, *qweqwe ]
```
