### ISSUE TITLE
Support unity-specific syntax

### ISSUE THREAD

**Issue by JohannesDeml** [redhat-developer/vscode-yaml#659]
## Summary
I mapped Unity's .asset files to yaml and it all works great, thanks for all your hard work!
However, there is one thing that is bothering me. Every Unity asset file (e.g. ScriptableObjects) has on line three a unity-specific syntax line: `--- !u!114 &11400000`
![Screenshot 2021-12-08 at 08 45 19](https://user-images.githubusercontent.com/4518980/145168911-6441c7e1-df11-42e6-ad39-9c487ddb3ed7.png)

Is there a way to allow this this syntax, so it does not show up as an error anymore?

## Relevant information
Running VS Code 1.62.3 with YAML 1.2.2
Here is an example of a unity asset file:
```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &11400000
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 27c29ed6e3c24f93865b4bc2df8b9c73, type: 3}
  m_Name: ExportAssetizerExamples
  m_EditorClassIdentifier: 
  assetPaths:
  - Assets/AssetizerExamples
  exportOptions: 2
  targetFile: Builds/AssetizerExamples-{Version}.unitypackage
  zipFile: 1
```
