### ISSUE TITLE
How to disable validation for conda meta.yaml?

### ISSUE THREAD

**Issue by alanwilter** [redhat-developer/vscode-yaml#665]
## Summary

Conda `meta.yaml` has some elements of `jinja` so this mix play havoc with yaml or jinja validation tools.

## Relevant information

For example:
```yaml
{% set data = load_setup_py_data() %}
{% set version = data.get('version')  %}

package:
  name: my_conda_app
  version: {{ version }}
...
```
`vscode-yaml` won't work on such file. How can I circumvent it? Or disable it? I tried to add an empty json schema or refer to itself, but I can't get rid to the problems messages.

```yaml
# yaml-language-server: $schema=./meta.yaml
```
or
```yaml
# yaml-language-server: $schema=./.empty_schema.json
```
where `.empty_schema.json` is just `{}`, won't work.
