### ISSUE TITLE
support go templates

### ISSUE THREAD

**Issue by cjroebuck** [redhat-developer/vscode-yaml#68]
I'm adding some go template syntax in my YAML which is causing this linter to complain, which is a shame. For e.g somewhere inside a kubernetes pod spec:

    spec:
      volumes:
      - name: fonts
        emptyDir: {}
      {{ if .development -}}
      - name: srccode
        hostPath:
          path: /Users/src
      {{- end }}

![image](https://user-images.githubusercontent.com/12208/36443820-b597726a-1671-11e8-98d3-8d91933d3c2b.png)

Any easy way to get it to ignore this go-template syntax?

**Comment by JPinkney** [comment]
There isn't any easy way to ignore the syntax that I can think of that isn't an extremely hacky solution like to hide fields that begin with {{ and end with }} from the parser. 

@gorkem Is that something you think we should look at/do you have any ideas about this?

**Comment by gorkem** [comment]
The given example is not legal YAML. Perhaps you can use string literals with `|` or `>`
Something like below which is legal YAML
```yaml
spec:
  volumes:
  - name: fonts
    emptyDir: | 
            {}
            {{ if .development -}}
  - name: srccode
    hostPath:
      path: /Users/src
```
