### ISSUE TITLE
Is it possible to define schema for custom tags?

### ISSUE THREAD

**Issue by jindong-zhang-git** [redhat-developer/vscode-yaml#680]
## Summary

Hi team, I have a custom tag `!include` with 2 properties `source` and `path`.

Usage case:

```yaml
object:
  <<: !include
    source: './abc/xyz'
    path: anyField
```

For now I have added it into `yaml.customTags` in settings: `"yaml.customTags": ["!include mapping"]`. 

No errors. Great!

But I hope to add additional checks on it, such as tagging `source` and `path` as required. Is it possible? And how should I to implement it? Thanks.

**Comment by evidolob** [comment]
>But I hope to add additional checks on it, such as tagging source and path as required. Is it possible? And how should I to implement it? Thanks.

That is not possible, as we use JSON Schema to validate yaml, and JSON schema doesn’t have any notion for yaml tags.

Maybe we can add non standard extension for JSON Schema to add definition/validation for yaml tags. 
@gorkem WDYT?

**Comment by jindong-zhang-git** [comment]
@evidolob Thanks for your reply. 

Since I can't check it, can I ignore this fragment during validation?
```yaml
<<: !include
  source: './abc/xyz'
  path: anyField
```

**Comment by evidolob** [comment]
Unfortunately no, we don’t have such feature

**Comment by jindong-zhang-git** [comment]
Oops, what a bad news.

Currently I meet some issue on validating yaml with `!include` tag:

```yaml
object:
  <<: !include
    source: './abc/xyz'
    path: anyField
  objectProperty: xxx
```

In above example, the validator will see `source` and `path` as `object`'s properties incorrectly. And obviously `object` doesn't support these two properties. So that there will be a validation error.

For me if I can tell validator that please don't check fragments start with `<<`, it's enough to solve my problem. Any ideas?
