### ISSUE TITLE
Failure to properly interpret github workflows schema

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-yaml#691]
## Describe the bug

I discovered a bug in yaml language server which makes it confused and report a false positive with current github-workflows schemas, even if these schemas are valid, tested (ajv) to ensure they accept that values.

![](https://sbarnea.com/ss/Screen-Shot-2022-02-04-10-41-05.39.png)

```
on:
  create:
    tags:  # <-- this is valid but extension believes create should only allow arrays
    - "**"
```

Schema: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json

postive-test file for that schema that includes the our bug https://github.com/SchemaStore/schemastore/blob/master/src/test/github-workflow/918.json#L5

## Expected Behavior
Pass validating with schemas that are already tested.

## Current Behavior

`Property tags is not allowed.` is reported when it should not be.

## Steps to Reproduce
1. create a file under `.github/workflows/sample.yml`
2. put the snipped above in it
3. check for false positive result
