### ISSUE TITLE
Formating removes vertical alignment of values

### ISSUE THREAD

**Issue by madpipeline** [redhat-developer/vscode-yaml#695]
## Describe the bug
When formatting the whitespace used for vertical alignment of values is removed, even though the YAML specs allow and encourage it.

Currently there is no way to work around this issue except by disabling the formatter. Installing the Prettier extension keeps the alignment but does not enforce it (by default).

## Expected Behavior
When formatting, values vertical alignment to be kept or added
```yaml
tree:
    fruit:    "pear"
    name:     "peartree"
    location: "garden"
```

## Current Behavior
Regardless of how they are vertically aligned, they the whitespace is stripped.
```yaml
tree:
    fruit: "pear"
    name: "peartree"
    location: "garden"
```

## Steps to Reproduce
1. Write any YAML file and align the values vertically using spaces
2. Format the file using this plugin's formatter
3. Alignment is broken

## Environment
- [x] Linux

**Comment by wiryonolau** [comment]
Moving from atom to vscode. Really needed this especially for ansible playbook

**Comment by blerrgh** [comment]
+1 on this. For yaml configuration files vertical alignment really makes a big difference in readability.

**Comment by adeqecil** [comment]
Still no updates till this day

**Comment by SimonG-Alza** [comment]
It would be nice to be able to align the values as Intellij Idea do.

**Comment by ufukty** [comment]
YAML Spec contains couple examples showing 2 versions of vertical alignment:

Example 2.4 aligns by value
```yaml
-
  name: Mark McGwire
  hr:   65
  avg:  0.278
-
  name: Sammy Sosa
  hr:   63
  avg:  0.288
```

Example 2.12 aligns by colons
```yaml
---
# Products purchased
- item    : Super Hoop
  quantity: 1
- item    : Basketball
  quantity: 4
- item    : Big Shoes
  quantity: 1
```

- https://yaml.org/spec/1.2.2/#chapter-2-language-overview
- https://stackoverflow.com/a/76446386/10272920
