### ISSUE TITLE
CloudFormation ref in `functions.fnName.layers` shows validations errors `Incorrect type. Expected "string".`

### ISSUE THREAD

**Issue by Shereef** [redhat-developer/vscode-yaml#698]
https://github.com/serverless/serverless/issues/10688#event-6056125643

CloudFormation ref in `functions.fnName.layers` shows validations errors `Incorrect type. Expected "string".yaml-schema: Serverless Framework Configuration`

![image](https://user-images.githubusercontent.com/356763/153695586-030b8c21-41d8-42cb-a346-20e492c3ce55.png)

it's a minor inconvenience because VS keeps saying I have an issue there for each function that uses the layer

![image](https://user-images.githubusercontent.com/356763/153695601-66c9d004-d7b5-4e85-a5ec-d59d380f44f8.png)

I can make a PR for this if someone were to point me in the right direction!

### Service configuration (serverless.yml) content

```yaml
healthCheck:
        handler: dist/src/health/check/handler.check
        layers:
            - { Ref: SharedLambdaLayer } # This is where the error happens
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
npx serverless --version
Framework Core: 3.2.0 (local)
Plugin: 6.0.0
SDK: 4.3.1
```
