### ISSUE TITLE
Yaml errors after updating to v1.5.0

### ISSUE THREAD

**Issue by Yoda-Man** [redhat-developer/vscode-yaml#708]
I am getting Yaml errors after updating to v1.5.0

**Comment by wer-mathurin** [comment]
Same thing here, there is a conflict with the pubspec.yaml (for dart), it report errors, while there is not error in the definition.

**Comment by evidolob** [comment]
@Yoda-Man @wer-mathurin Could you provide yaml samples/files where you getting errors?

**Comment by cluedtke** [comment]
Started receiving errors in my openapi yaml files after updating as well ([OpenAPI (Swagger) Editor](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi) is dependent on this extension). If it helps, here's a minimal reprod:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/16242970/157055640-5004363c-9ceb-4e8f-93d4-28f747017f59.png">

**Comment by jorasinghr** [comment]
![image](https://user-images.githubusercontent.com/40352266/157067033-6d2c2137-a8f4-47a4-a037-0cabbda22be4.png)
Github action error on environment, rollback to 1.4.0 works.

**Comment by fastlorenzo** [comment]
Same here with `pubspec.yaml` file (Flutter):

```yaml
name: app
description: application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^1.4.0
  firebase_auth: ^3.3.7
  # firebase_auth_oauth: ^1.1.0
  firebase_auth_oauth:
    git:
      url: git://github.com/fastlorenzo/firebase_auth_oauth.git
      path: firebase_auth_oauth
  firebase_auth_oauth_web:
    git:
      url: git://github.com/fastlorenzo/firebase_auth_oauth.git
      path: firebase_auth_oauth_web
  google_sign_in: ^5.2.4-nullsafety
  cloud_firestore: ^3.1.8
  rxdart: ^0.27.0
  flutter_signin_button:
  get: ^4.6.1
  vrouter: ^1.2.0
  provider: ^6.0.2
  google_fonts: ^2.3.1
  flex_color_scheme: ^4.2.0
  image_picker: ^0.8.4
  signature: ^5.0.0
  json_annotation: ^4.4.0
  uuid: ^3.0.6
  cupertino_icons: ^1.0.2

dependency_overrides:
  firebase_auth_oauth_web:
    git:
        url: git://github.com/fastlorenzo/firebase_auth_oauth.git
        path: firebase_auth_oauth_web
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
```

Downgrading to extension v1.4.0 no longer throws errors.

**Comment by bryson** [comment]
```yaml
name: foo
on:
  push:
    branches:
      - "*"

jobs:
  foo:
    runs-on: ubuntu-latest
    env:
      bar_path: ${{ github.workspace }}/bar.json
```
Error flagged the last line for `bar_path`:

> `Incorrect type. Expected "boolean". yaml-schema: GitHub Workflow`

**Comment by xiaocode337317439** [comment]
flutter pubspec.yaml  error
me too

**Comment by gorkem** [comment]
Looks like reverting https://github.com/redhat-developer/yaml-language-server/commit/99fd9f07aa917d6debb605f2922910e2dcbbc5ad is fixing the issue.

**Comment by amirul12** [comment]
Suddenly I am facing pubspect.yaml error, how I can solve this and run my project.

**Comment by msivasubramaniaan** [comment]
@gorkem I have reverted the changes https://github.com/redhat-developer/yaml-language-server/pull/676 please review and approve the PR and as mentioned we will release 1.5.1 version and I am planning to work on the issue with best solution

**Comment by okan-oz** [comment]
flutter pubspec.yaml error
me too

**Comment by bricker** [comment]
@msivasubramaniaan Thank you, the 1.5.1 release fixed this for me.

**Comment by msivasubramaniaan** [comment]
Can anyone share the corresponding schema and YAML file for this issue. I need figure it out the root cause. It would be good if I get more combinations.

**Comment by bryson** [comment]
I shared this [above](https://github.com/redhat-developer/vscode-yaml/issues/708#issuecomment-1061105022), but the following short YAML will reproduce the issue for me: 

```yaml
name: foo
on:
  push:
    branches:
      - "*"

jobs:
  foo:
    runs-on: ubuntu-latest
    env:
      bar_path: ${{ github.workspace }}/bar.json
```
Error flagged on the last line for `bar_path`:

> `Incorrect type. Expected "boolean". yaml-schema: GitHub Workflow`
