### ISSUE TITLE
Syntax highlight for multiline string filled with code

### ISSUE THREAD

**Issue by macabeus** [redhat-developer/vscode-yaml#714]
### Is your enhancement related to a problem? Please describe.

It's pretty common to use a YAML file having a multiline string filled with code.

For instance, when is working with GitHub Actions, the `run` field can be filled with a shell script code:
```yml
jobs:
  example:
    runs-on: ubuntu-20.04
    steps:
    - name: Blah
      run: |
        echo "foo"
        echo "bar"
```

But since there is no way to use this extension and have syntax highlight on this part, it became monochrome.
It's okayish for simple code, but it makes harder to read a more complex code:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/9501115/158064919-36712777-90cc-45e6-964a-fd5ee557a6a9.png">

### Describe the solution you would like

We can read the first line for a multiline string and check if there is a shebang.
If there is one, it imports the syntax highlight for the given language.

```yml
jobs:
  example:
    runs-on: ubuntu-20.04
    steps:
    - name: Blah
      run: |
        #!/bin/sh
        # from now on, this multiline string is syntax highlighted with the shell script grammar
        echo "foo"
        echo "bar"
```

**Comment by michaeltlombardi** [comment]
A potentially useful idea for an alternative implementation is to use the [`contentMediaType`][01] key to add syntax highlighting for a string if the property is schematized with it.

So for example, with this schema:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "foo": {
      "title: "Foo",
      "description": "A non-markdown string",
      "type": "string"
    },
    "some_markdown": {
      "title": "Some Markdown",
      "description": "The text of this property is always treated as markdown",
      "type": "string",
      "contentMediaType": "text/markdown"
    }
  }
}
```

This YAML file would have the `some_markdown` key highlighted as markdown but not the `foo` key:

```yaml
foo: This highlights normally (i.e. it _doesn't_)
some_markdown: |
  This highlights as `markdown`.
```

This would only work with [defined media types][01], which is a limited list and mostly doesn't include code, but I often find myself wishing my markdown strings in yaml at least had highlighting.

I think the shebang idea would be useful. It's also worth noting that, for GHA files in particular, the GitHub Action extension itself could provide highlighting with injection grammar, since that extension isn't trying to support arbitrary YAML files with a schema. There's also an [issue filed][02] in that repo for this same feature.

[01]: https://www.iana.org/assignments/media-types/media-types.xhtml#text
[02]: https://github.com/cschleiden/vscode-github-actions/issues/144

**Comment by connorjs** [comment]
Does anyone know if comments are included in the YAML AST and, if so, if they could be used as a hint for syntax highlighter?

For example, I was thinking of `lang=sh` or `lang=js`, which some markdown renderers use.

```yaml
#lang=sh
foo: |
  echo hi

#lang=js
bar: |
  console.log('hi')
```

I like the shebang idea, but I feel that would require O(n) in number of supported languages.

I also like the media type approach. It would provide a way to configure it for some use cases. However, I do like the idea of an in-document hint.

Again, I have no idea about how the YAML AST (and dependent on the parser I guess) handles the comment token in my proposal.

_Context: Thinking about this for GitHub workflows/actions specifically._
