### ISSUE TITLE
Incorrect schema validation of molecule configuration files

### ISSUE THREAD

**Issue by mbihoop** [redhat-developer/vscode-yaml#728]
## Describe the bug

Molecule configuration validation produces a lot of false positives, and I can't figure out how to disable validation (I suffer from major OCD so the red lines drive me mad :-) ) 

Given the following (valid) `molecule/default/molecule.yml` file (with a couple of confidential things xxx'd out)...

```yaml
---
dependency:
  name: galaxy
  options:
    ignore_certs: true
    requirements-file: requirements.yml
    #    v: true
driver:
  name: vagrant
platforms:
  - name: xxxx.xxxx
    box: rhel8-xxx
    box_version: 0.0.1
    box_url: http://localhost/vagrant/metadata/xxx.json
    memory: 4096
    cpus: 4
    interfaces:
      - network_name: private_network
        type: static
        ip: xxxxxxxx
provisioner:
  name: ansible
  ansible_args:
    - --inventory= ../../ci_inventory/inventory
  config_options:
    defaults:
      vault_password_file: ~/key
  env:
    ANSIBLE_ROLES_PATH: ../../roles
    ANSIBLE_SSH_COMMON_ARGS: '-o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null"'
    ANSIBLE_COLLECTIONS_PATH: $MOLECULE_EPHEMERAL_DIRECTORY/collections
verifier:
  name: ansible
lint: |
  set -ex
  yamllint .
  ansible-lint
```

I get the following validation errors: 

```
[{
	"resource": "xxxx/molecule/default/molecule.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property box_version is not allowed.",
	"source": "yaml-schema: MoleculePlatformModel",
	"startLineNumber": 13,
	"startColumn": 5,
	"endLineNumber": 13,
	"endColumn": 16
},{
	"resource": "xxxxx/molecule/default/molecule.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property box_url is not allowed.",
	"source": "yaml-schema: MoleculePlatformModel",
	"startLineNumber": 14,
	"startColumn": 5,
	"endLineNumber": 14,
	"endColumn": 12
},{
	"resource": "xxxxx/molecule/default/molecule.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property interfaces is not allowed.",
	"source": "yaml-schema: MoleculePlatformModel",
	"startLineNumber": 17,
	"startColumn": 5,
	"endLineNumber": 17,
	"endColumn": 15
},{
	"resource": "xxxxx/molecule/default/molecule.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property ansible_args is not allowed.",
	"source": "yaml-schema: ProvisionerModel",
	"startLineNumber": 23,
	"startColumn": 3,
	"endLineNumber": 23,
	"endColumn": 15
},{
	"resource": "xxxxx/molecule/default/molecule.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property vault_password_file is not allowed.",
	"source": "yaml-schema: ProvisionerConfigOptionsDefaultsModel",
	"startLineNumber": 27,
	"startColumn": 7,
	"endLineNumber": 27,
	"endColumn": 26
}]
```

## Expected Behavior

Valid schema and correct validation applied.

## Current Behavior

Incorrect schema and invalid validation applied.

## Steps to Reproduce

Take the provided (valid) file as test input, apply the schema against it.

## Environment

All operating systems
