### ISSUE TITLE
How to disable schema validation entirely? 

### ISSUE THREAD

**Issue by 0x412e4e** [redhat-developer/vscode-yaml#733]
## Summary
Is there a way I could disable the schema validation for all of my playbooks? I couldn't find it in the YAML or Ansible module's settings.

I've been having a problem with vscode-YAML's validation scheme after some update.
## Relevant information

I have a simple playbook in which I use import_tasks to run other playbooks. 

```yaml
    - name: Linux tasks
      block:
        - name: tasks1
          import_tasks: tasks1.yml

        - name: tasks2
          import_tasks: tasks2.yml

      when: ansible_system == "Linux"
```

Because of the YAML schema validation every single task in `tasks1.yml` or `tasks2.yml` gives the following error:

`Missing property "import_playbook".yaml-schema: ImportPlaybookModel`
