### ISSUE TITLE
false schema error in github workflows file

### ISSUE THREAD

**Issue by rbtcollins** [redhat-developer/vscode-yaml#738]
I don't know if this is a bug in the schema definition or in the yaml extension.

The project I'm working on (https://github.com/XAMPPRocky/remove_dir_all) has the following content in a workflow file:

```
jobs:
  build-unix:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        channel: [stable, beta, nightly]
        os: [ubuntu, macos]
```

This is valid: the variable is substituted across the matrix. Each resulting value is e.g. macos-latest. But the yaml extension in vscode reports this error:

```
Value is not accepted. Valid values: "macos-10.15", "macos-11", "macos-latest", "self-hosted", "ubuntu-18.04", "ubuntu-20.04", "ubuntu-latest", "windows-2016", "windows-2019", "windows-2022", "windows-latest".
```

Yaml extension version 1.6.0
