### ISSUE TITLE
Confusing "Property is not allowed" #614

### ISSUE THREAD

**Issue by Almazatun** [redhat-developer/vscode-yaml#762]
## Describe the bug
**👉 vscode 1.66.2**
**👉 extension version v1.7.0**

I have faced issues. I found a discussion with closed mark #614 which means that it should be fixed, but it still exists.

![image](https://user-images.githubusercontent.com/50825098/165581332-16eee7e0-d37b-4e26-9cbb-624582e6365e.png)
![image](https://user-images.githubusercontent.com/50825098/165584947-48d6ed1a-860a-426f-83c5-c86d56c5e50a.png)

**Yaml file**
```yaml
CreateResumePathWithID:
  post:
    tags:
    - Resume
    summary: Create resume
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          #uuid
          example: "00000000-0000-0000-0000-000000000000"
```

I did some research to try to find how I can fix the issue. I just rename the file from `resume.yaml` to `resum.yaml` and the error message is gone. But I still think that is not a good idea to solve it in that way.

Please fix that issue.

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)
