### ISSUE TITLE
formatter removes end of document (...) directive.

### ISSUE THREAD

**Issue by mayur-who** [redhat-developer/vscode-yaml#765]
I have yaml file like this:

```
---
tenantName: testTenant
actions:
- action: create
  objectType: tenant
  tenant:
    num: 2
    name: testTenant
...
---
tenantName: testTenant
actions:
- action: create
  objectType: attribute
  signal:
    name: helloAttrOld
...
---
tenantName: testTenant
actions:
- action: update
  objectType: attribute
  attributeName: helloAttrOld
  attribute:
    name: helloAttr
...
---
# similar things
...
---
tenantName: testTenantTemporaryRename
actions:
- action: update
  objectType: tenant
  tenant:
    name: testTenant
...
```

But the auto formatter just removes the end of document directives (...) and only keeps the start of the document directive (---).
is there something that I can configure to get around it?

Environment: linux
