### ISSUE TITLE
Schema validation breaks when using artifactName alias property on PublishPipelineArtifact@1 task

### ISSUE THREAD

**Issue by Charles-Gagnon** [redhat-developer/vscode-yaml#800]
Example : PublishPipelineArtifact@1 has a property named `artifact` with an alias of `artifactName`

https://github.com/microsoft/azure-pipelines-vscode/blob/main/service-schema.json#L20009

If you make a yml with this content : 

```
steps:
  - task: PublishPipelineArtifact@1
    displayName: Demo
    inputs:
      artifactName: MyArtifact
```

then you get this error

`DownloadPipelineArtifact is deprecated - Download a named artifact from a pipeline to a local path`

So for some reason it seems to think that this is the `DownloadPipelineArtifact` task, although that may be a side effect of something else breaking
