### ISSUE TITLE
Composite action arguments error

### ISSUE THREAD

**Issue by br4ch1st0chr0n3** [redhat-developer/vscode-yaml#828]
## Describe the bug

Hi, I use YAML + GitHub Workflow schema + [composite actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions)

## Expected Behavior

No errors

## Current Behavior

![image](https://user-images.githubusercontent.com/48378098/191792944-0ac82f98-4672-4c9a-bbbd-dcf2a81f733c.png)

## Steps to Reproduce

Here are several snippets:

- `settings.json`
```json
{
    "yaml.schemas": {
        "https://json.schemastore.org/github-action.json": "**/actions/**/action.yml",
        "https://json.schemastore.org/github-workflow.json": "**/workflows/**/*.yml"
    }
}
```

- `workflow.yaml`:
```yaml
steps:
  - name: Cache ${{ env.root }}
    uses: ./.github/actions/each-devshell
    with:
      ROOT: ${{ env.root }}
      SHELLS: ${{ env.root_devShells }}
```

- `action.yml`:
```yaml
inputs:
  ROOT:
    description: a dir for which this action should be run
    required: true
  SHELLS:
    description: devShells names
    required: true
```

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)
