### ISSUE TITLE
incorrect behavior of keys with quotes 

### ISSUE THREAD

**Issue by Dimus99** [redhat-developer/vscode-yaml#842]
## Describe the bug
when autocomplete keys with quotes are not put quotes

schema:
```
additionalProperties: false
properties:
  validation:
    type: object
    additionalProperties: false
    properties:
      "null":
        type: boolean
        default: false
```

behavior:

https://user-images.githubusercontent.com/47976394/200510836-57c0e2d5-ce29-4b6b-beb1-4e10d59bb70a.mov

## Expected Behavior
The key will be inserted with quotes

## Current Behavior
the key is sometimes inserted without quotes

## Environment
-  Mac
