### ISSUE TITLE
Added tag to customTags, get error on tag

### ISSUE THREAD

**Issue by doapp-ryanp** [redhat-developer/vscode-yaml#85]
My userSettings:
```json
{
    "editor.formatOnSave": true,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "editor.minimap.enabled": false,
    "workbench.statusBar.visible": false,
    "go.useLanguageServer": true,
    "go.docsTool": "gogetdoc",
    "extensions.ignoreRecommendations": false,
    "php.suggest.basic": false,
    "yaml.format.enable": true,
    "yaml.customTags": [
        "!Ref",
        "!Sub",
        "!GetAtt",
        "!Select",
        "!Split"
    ]
}
```

```yaml
...
  APIGAccount: 
    Type: "AWS::ApiGateway::Account"
    Properties: 
      CloudWatchRoleArn: !GetAtt APIGCloudWatchRole.Arn
...
```

Error:
```
[Error - 08:29:10] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: unknown tag !<!GetAtt> at line 75, column 56:
     ... : !GetAtt APIGCloudWatchRole.Arn
```

Any ideas?  This line is the 1st line in my yml with a custom tag.  IDE showed a red squiggly under the !GetAtt tag until I added it to `yaml.customTags` (then red went away).  Doesn't break until I format the  doc.  My guess is the formatter does not yet have support for `yaml.customTags`?
