### ISSUE TITLE
Incorrectly formatted code

### ISSUE THREAD

**Issue by asispts** [redhat-developer/vscode-yaml#855]
## Describe the bug
This code will be formatted incorrectly.
```yaml
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
```

## Expected Behavior
Should be formatted like the original code.

## Current Behavior
The code is formatted as
```yaml
when@test:
    security:
        password_hashers:
            ? Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface
            : algorithm: auto
              cost: 4
```

## Steps to Reproduce
Open vscode and try formatting the code.

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

```
vscode: v1.73.0
yaml ext: v1.10.1
```
