### ISSUE TITLE
Better error message when a `$ref` attribute fails validation

### ISSUE THREAD

**Issue by stdedos** [redhat-developer/vscode-yaml#864]
### Is your enhancement related to a problem? Please describe.
For the gitlab-ci-schema plus

```json
              ,
              "variables": {
                "markdownDescription": "Additional environment variables that are passed exclusively to the service. The syntax is the same as [Job Variables](https://docs.gitlab.com/ee/ci/variables/index.html).",
                "$ref": "#/definitions/jobVariables"
              }
```

in `services:`, input:

```yaml
test_docker_image_with_service:
  services:
    - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      alias: service-under-test
      variables:
        - PORT: ${PORT}
```

gives:

![image](https://user-images.githubusercontent.com/133706/210779267-5e5d57a1-312d-4af8-a59d-74e213ab4212.png)

which a very weird way of saying "please remove that `-` from inside `variables:`".

### Describe the solution you would like

- Error message should be more clear.
- Also, maybe, "not provide schema-internal information" on the forefront (acceptable on `--verbose`)
