### ISSUE TITLE
Strange behavior on format

### ISSUE THREAD

**Issue by Vincz** [redhat-developer/vscode-yaml#90]
Hi!
Since yesterday, when I format a YAML file on save, it add the following header

```
_uri: 'file:///<path_to_my_file>.yaml'
_languageId: yaml
_version: 642
_content: |
  <content_of_my_file>
_lineOffsets:
    - 0
    - 9
    - 19
```

Any idea?

**Comment by Vict0rSch** [comment]
Same here, version `0.0.13`, vscode  `1.24.0`

**Comment by JPinkney** [comment]
It most likely went wrong during [this commit](https://github.com/redhat-developer/yaml-language-server/commit/191274a3aeadde275d02714257bb66c74bd4cd03). I should have a fix+release in the next week.

**Comment by mikehanney** [comment]
Format document goes more wrong when the end of line format is CRLF compared to when it is LF. Just saying in case it helps troubleshoot.

**Comment by tizmagik** [comment]
Just hit this today too, vscode 1.24.1

**Comment by JPinkney** [comment]
It will be fixed in the release Monday! (There will be completely new formatter that preserves comments)

**Comment by shawnhwei** [comment]
Any update on this?

**Comment by Southclaws** [comment]
I cloned the repo and built a .vsix to test, the formatted seems fixed in the latest commit! Just needs to be released to the marketplace, if there are no other issues of couse.

**Comment by shawnhwei** [comment]
Can we offer any help with the Jenkins issue? Would really like to get this fix on our machines.

**Comment by JPinkney** [comment]
You can try checking out this repository, then running npm install vsce -g then running vsce package and tell me if anything goes wrong (it works fine on both my computers). Unfortunately I'm not the one who approves the releases so it may take some time.

**Comment by JPinkney** [comment]
Just released the newest version. Unfortunately I wasn't able to get the new formatter in but atleast this issue is now resolved.

**Comment by Southclaws** [comment]
I just saved a travis config and got some extremely odd and quite funny results:

Before save:
```yaml
sudo: required
services:
  - docker
before_install:
  - "sudo dpkg --add-architecture i386"
  - "sudo apt-get install -qq --force-yes build-essential gcc-multilib g++-multilib > /dev/null"
addons:
  apt:
    packages:
      - docker-ce
language: go
jobs:
  include:
    - stage: test smallbits
      script:
        - go test -race -v -p 4 -coverprofile=coverage.txt ./versioning ./util ./download ./compiler
        - bash <(curl -s https://codecov.io/bash)
    - stage: test runtime
      script:
        - go test -race -v -p 4 -coverprofile=coverage.txt ./runtime
        - bash <(curl -s https://codecov.io/bash)
    - stage: test rook
      script:
        - go test -race -v -p 4 -coverprofile=coverage.txt -timeout=20m ./rook
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      if: branch =~ ^(v?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?)$
      script:
        - test -n "$TRAVIS_TAG"
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes gcc-multilib > /dev/null; fi
        - sudo apt-get install -y build-essential rpm
        - gem install --no-ri --no-rdoc fpm
        - curl -sL https://git.io/goreleaser | bash
go:
  - "1.10"
```

After save:

```yaml
sudo: required
?
  service
: - - dock
? r
  before_inst
: - ' - "sudo dpkg --add-architecture '
  - '  - "sudo apt-get install -qq --force-yes build-essential gcc-multilib g++-multilib > /dev'
ull":
  ns::
    t::
      -
        -
ocker-ce: la
guag:
  ? o
    jobs
  : - lude::     - stage: t
      llbits:
        - pt:
          - go test -race -v -p 4 -coverprofile=coverage.txt ./versioning ./util ./down
        - iler
          - bash <(curl -s https://
    - .io/b: h)
        - st
      st run:
        - script:
          - go test -race -v -p 4 -coverprofile=cov
        - /runtime
          - bash <(curl -s http
    - ecov.: /bash)
      age: t:
        -     script:
          - go test -race -v -p 4 -coverprofile=coverage.
        - t=20m ./rook
          - bash <(curl -s
    - /code: v.io/b
      :  stage: deploy
        if: branch =~ ^(v?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\d
      ?:\.[\:
        - $
          script:
        -  -n "$TRAVIS_TAG"
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCK
        - " --password-stdin
          - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-ye
        - lib > /dev/null; fi
          - sudo apt-get
        -  build-essential rpm
          - g
        - --no-ri --no-rdoc fpm
          - curl -sL
ht:
  - "it.i"
```
