### ISSUE TITLE
"Unable to load schema" when using `$id`

### ISSUE THREAD

**Issue by EmilySeville7cfg** [redhat-developer/vscode-yaml#922]
## Describe the bug

> Problems loading reference 'http://emily.json/#a': Unable to load schema from 'http://emily.json/': Request vscode/content failed unexpectedly without providing any details. error.

when using `$ref` in:

```yaml
{
    "$id": "http://emily.json",
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "first": {
            "$id": "#a",
            "type": "boolean"
        },
        "second": {
            "$ref": "http://emily.json#a"
        }
    }
}
```

## Expected Behavior
Successful reference resolution.

## Current Behavior
Failed resolution.

## Steps to Reproduce

1. Create **schema.json** with:

```json
{
    "$id": "http://emily.json",
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "first": {
            "$id": "#a",
            "type": "boolean"
        },
        "second": {
            "$ref": "http://emily.json#a"
        }
    }
}
```

content.

2. Create **test.yaml** with:

```yaml
first: true
```

content.

3. Create **.vscode/settings.json** with:

```json
{
    "yaml.schemas": {
        "schema.json": "test.yaml"
    }
}
```

content.

4. Open **test.yaml** and obtain mentioned error

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)

## Related issue

https://github.com/json-schema-org/json-schema-spec/issues/1398
