### ISSUE TITLE
.gitlab-ci.yml - Custom tag !reference defined in schema but reported as error.

### ISSUE THREAD

**Issue by gone-for-coding** [redhat-developer/vscode-yaml#925]
## Expected Behavior
This code is actually valid:

.gitlab-ci.yml
```yaml
.common:
  before_script:
    - git config --global credential.helper store

.job:
  before_script:
    - !reference [.common, before_script]
```

The correct schema is loaded:
https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L1732
https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/assets/javascripts/editor/schema/ci.json#L29

## Current Behavior
Problems are raised for each !reference tag in the file:
Unresolved tag: !reference

## Steps to Reproduce
Use the above mentioned file.

## Environment
- [X ] Windows
- [ ] Mac
- [ X] Linux
- [ ] other (please specify)
