### ISSUE TITLE
Inaccurate YAML validation errors

### ISSUE THREAD

**Issue by andyeff** [redhat-developer/vscode-yaml#94]
Hello,

Since Tuesday or Wednesday this week, I've started noticing the YAML validation has started flagging up things seemingly incorrectly.

I primarily write YAML for Ansible playbooks and don't recall seeing this at any point earlier so unsure what might have changed, but for example:

```
- name: "Copy CA certs to {{ inventory_hostname }}"
  win_copy:
    src: "{{ env }}/RootCA.cer"
    dest: c:\temp\ssl-certs\
- win_copy:
    src: "{{ env }}/subca.cer"
    dest: c:\temp\ssl-certs\
- win_copy:
    src: "{{ env }}/bluecoat.crt"
    dest: c:\temp\ssl-certs\
```
The second and third win_copy tasks are now showing `Missing property "name".` 

Another example
```
# Configure AZ
- block:
  - name: "Configure AZ1"
    set_fact:
      az: "az1"
    when: "'az1' in group_names"
```
The block keyword is flagged as having an issue with: `Missing property "script".`

My extension prefs are:
```
   "[yaml]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": false
        },
        "editor.autoIndent": false
    },
    "yaml.validate": true,
    "yaml.customTags": ["!vault"]
```

This is with VS Code 1.24.1 and redhat.vscode-yaml 0.0.13

Unfortunately I don't know much about how VS Code extensions work, so can't easily tell if this is something since the extension was updated to v0.0.13 - is it possible for me to go back to the previous version and test whether validation is still working ok?
