### ISSUE TITLE
Support syntax highlight from different language for multi-line strings with a special comment

### ISSUE THREAD

**Issue by felipecrs** [redhat-developer/vscode-yaml#943]
### Is your enhancement related to a problem? Please describe.
I have a bunch of YAML files that embeds XML, JSON, Bash Scripts, Dockerfiles, and so on. When opening them in VS Code, such inline strings are interpreted as plain strings, which makes it a little difficult to edit.

### Describe the solution you would like

To support syntax highlight of other languages for multi-line strings block that has a special comment. For example:

```yaml
javascript: | # yaml-language-server: $language=javascript
  console.log('hi')
json: | # yaml-language-server: $language=json
  {
    "hello": "world"
  }
```

### Describe alternatives you have considered

Extract the file to its own window, make the changes and then copy it back to the YAML file. Having syntax highlight directly in the YAML file would be a huge time saver :).

### Additional context

It looks like this can be implemented in vscode through something like this: https://github.com/Microsoft/vscode-extension-samples/tree/main/decorator-sample
