### ISSUE TITLE
Renamed docker-compose YAML files use incorrect schema despite file association

### ISSUE THREAD

**Issue by rcdailey** [redhat-developer/vscode-yaml#947]
## Describe the bug

I have a Docker Compose YAML file with the following name:

```txt
docker-compose.test.yml
```

It has the following contents:

```yml
services:
  test:
    image: postman/newman:alpine
    build: context
    networks: [my_network]
    depends_on: [deployment]
    environment:
      - app_url=deployment:80
    volumes:
      - ./postman:/etc/newman:ro
    command: >-
      run my.postman_collection.json --reporters junit,cli
```

I noticed that there was a red-squiggly under `services`. When hovering over that, it said it was using `prometheus.rules.test.json` as the schema. So I went to my workspace `settings.json` and added this:

```json
"files.associations": {
  "docker-compose*.yml": "dockercompose",
}
```

After reloading VS Code, I noticed that the red-squiggly was still there. Apparently this file association isn't forcing the correct schema to be used, even though Language Mode is clearly set to `dockercompose`.

After googling some more, I found that this fixes the issue:

```json
"yaml.schemas": {
  "https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json": "docker-compose*.yml"
},
```

## Expected Behavior

My expectation is that the [docker compose schema](https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json) is used when language mode is set to `dockercompose` via `files.associations` setting in VS Code. I should not have to set the JSON schema explicitly.

## Environment

Windows 10
