### ISSUE TITLE
Add `$schema: ` syntax to load JSON schema for YAML files

### ISSUE THREAD

**Issue by carlosedp** [redhat-developer/vscode-yaml#958]
### Is your enhancement related to a problem? Please describe.

Recently, Intellij added a syntax to load a JSON schema for YAML files in the format of `$schema: https://schemaURL`. It would be great if the YAML extension could also leverage this so we can have a single configuration parameter.

Sample:

```yaml
$schema: https://raw.githubusercontent.com/oyvindberg/bleep/master/schema.json
$version: 0.0.2
jvm:
  name: graalvm-java17:22.3.2
projects:
  httpserver:
    dependencies:
      - dev.zio::zio-http:3.0.0-RC2
      - dev.zio::zio:2.0.15
    extends: template-common
```

### Describe the solution you would like
YAML extension load a schema from `$schema:` line.

### Describe alternatives you have considered
Currently we need to configure settings.json or add a modeline in addition to the existing $schema for Intellij.
