### ISSUE TITLE
Double-space in `markdownDescription:` code block indentations rendered as literal `&emsp;`

### ISSUE THREAD

**Issue by LeShaunJ** [redhat-developer/vscode-yaml#960]
## Describe the bug

**VScode's** builtin `json` LSP extension recognizes the schema property, `markdownDescription:`, which prompts it to ignore `description:` and instead render the `markdown` provided. `vscode-yaml` is no different; however, it falls victim to the same issue that `examples:` (#959) faces.

That is to say, when `markdownDescription:` is rendered during a `hover`, double-spaces (`  `) are rendered as literal `&emsp;` if they occur as indentations within `<code>` blocks.

## Expected Behavior

When `hover` is called on a schema property and its `mardownDescription:` is rendered, double-space indentations within `<code>` blocks should appear as two spaces, as is the case with **VScode's** builtin offering for `json`:
> <img width="626" alt="image" src="https://github.com/redhat-developer/vscode-yaml/assets/5474674/7d34f452-0be9-48e8-a0e6-e9d4414e6a36">

## Current Behavior

When `hover` is called on a schema property and its `mardownDescription:` is rendered, double-space indentations within `<code>` blocks are replaced with the literal `HTMLEntity`, `&emsp;`:
> <img width="546" alt="image" src="https://github.com/redhat-developer/vscode-yaml/assets/5474674/a6017e43-911c-4f1f-b4b6-c949e2f34abe">

## Steps to Reproduce

1. Create a schema that utilizes `mardownDescription:`, with its content containing a `<code>` block that include **two space** indentations:
   ````yaml
   # schema.yaml (or schema.json, either/or)
   $schema: ...
   $id: ...
   type: object
   properties:
     edge_case:
       type: string
       description: A basic description of a thing.
       markdownDescription: |
         A detailed description of a thing.
         
         ## Note
         Beware of some gotcha in which something is not what it seems because of reasons. For example:
         ```yaml
         edge_case:
           prop: caveat
         ```
         This could result in whatever, might as well be lorem ipsum.
   ````
2. Create a `YAML` that is binding to the aforementioned schema:
   ````yaml
   # yaml-language-server: $schema=schema.yaml
   edge_case: {}
   ````
3. Hover over the offending property (_in this case, the `edge_case:` property_).
4. Note the literal `&emsp;` that has replaced the **two space** indentation before `prop:` in the rendered `<code>` block:
   > A detailed description of a thing.
   > 
   > ## Note
   > Beware of some gotcha in which something is not what it seems because of reasons. For example:
   > ```yaml
   > edge_case:
   > &emsp;prop: caveat
   > ```
   > This could result in whatever, might as well be lorem ipsum.

## Peculiarities

With all that said, this _is not_ the case when rendered during a "peek" of a `completion` suggestion:
> <img width="582" alt="image" src="https://github.com/redhat-developer/vscode-yaml/assets/5474674/74228a12-646e-4b90-a202-a0fbecad11d8">

Which pokes a hole in my initial hunch was that this was linked to #959; hence, why I create a separate issue.

## Workaround

Currently, the way to get around this is to exclusively use the `tab` character (`\t`) to indent `<code>` block content within `markdownDescrption`. Though, this is not ideal, as some languages (_like `YAML`_) consider `\t` as invalid indentation. Furthermore, `\t` is rendered at a length of `    `, which you also wouldn't want if `YAML` is target `<code>` block rendering.

## Environment

- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (WSL2)
