### ISSUE TITLE
Property names/keys with more than 80 symbols get prefixed with question mark ?, and colon : gets wrapped onto the next line

### ISSUE THREAD

**Issue by MurzNN** [redhat-developer/vscode-yaml#968]
## Describe the bug
I have a YAML file like this:
```yaml
services:
  Drupal\some\long\service\name\name\name\name\name\name\name\name\na\length_80:
    tags:
      - name: event_subscriber

  Drupal\some\long\service\name\name\name\name\name\name\name\name\nam\length_81:
    tags:
      - name: event_subscriber
```
And the formatter always changes it to the:
```yaml
services:
  Drupal\some\long\service\name\name\name\name\name\name\name\name\na\length_80:
    tags:
      - name: event_subscriber

  ? Drupal\some\long\service\name\name\name\name\name\name\name\name\nam\length_81
  : tags:
      - name: event_subscriber
```
So, names/keys with a length of more than 80 symbols get prefixed with the question mark `?`, and the colon `:` gets wrapped onto the next line.

## Expected Behavior
The formatter should keep the original formatting.

## Current Behavior
See above.

## Steps to Reproduce
1. Create a YAML file with the content in the first code block.
2. Format the file.
3. See the wrong changes.

## Environment
VS Code version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.0-27-generic
