### ISSUE TITLE
tabSize setting is inconsitently applied

### ISSUE THREAD

**Issue by FFdhorkin** [redhat-developer/vscode-yaml#976]
## Describe the bug
I have tabSize set to 4:
```json
"[yaml]": {
	"editor.insertSpaces": true,
	"editor.tabSize": 4,
	"editor.autoIndent": "keep",
	"diffEditor.ignoreTrimWhitespace": false,
	"editor.quickSuggestions": {
		"other": true,
		"comments": false,
		"strings": true
	}
}
```
`vscode-yaml` inconsistently applies the tab size, resulting in mixed indents of 4 and 6.

Here's an example of some yaml from a Github Action I'm working on that the extension should not be reformatting:

```yml
# ...
runs:
    using: "composite"
    steps:
    -   name: Setup environment variables
        id: env_vars
        run: |
            export AWS_REGION=us-west-2 >> $GITHUB_ENV
# ...
```
You can see in this screenshot that tab size is consistently 4 spaces:
![image](https://github.com/redhat-developer/vscode-yaml/assets/59899746/00e0420e-3c28-4b34-9404-d2af195782de)

## Expected Behavior
When formatting happens, the above should be left untouched

## Current Behavior
`vscode-yaml` removes the spaces after the hyphen and adds an unnecessary indent, reformatting to the following:
```yml
runs:
    using: "composite"
    steps:
        - name: Setup environment variables
          id: env_vars
          run: |
              export AWS_REGION=us-west-2 >> $GITHUB_ENV
```
This uses tab size 4 sometimes, other times tab size 2. The problem is removing the spaces after the hyphen... `-   name:` should **_not_** be changed to `    - name:`!

You can see in this screenshot that this is inconsistent tab size; `id` and `run` are _half_ indented:
![image](https://github.com/redhat-developer/vscode-yaml/assets/59899746/3e28f65b-5078-45b2-8188-bd5633e6984c)

This isn't a problem with tab size 2, since `- name:` is implicitly tab size 2.

## Steps to Reproduce
1. set tabSize to 4
2. run formatting

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)
