### ISSUE TITLE
YAML `---` for "Multiple documents within a single stream" doesn't work [VSC YAML Plugin]

### ISSUE THREAD

**Issue by vorburger** [redhat-developer/vscode-yaml#995]
I wrote my first trivial JSON schema `enola.schema.jsonc`, like this:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://docs.enola.dev/json-schema/enola_meta.schema.jsonc",
  "title": "Enola.dev Meta Model",
  "description": "See https://docs.enola.dev",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "Short technical name of this Type."
    }
  },
  "required": ["name"]
}
```

Then I wrote an `test.yaml` file using that schema, like this:

```yaml
# yaml-language-server: $schema=enola.schema.jsonc

name: enola.dev/url
doc: enola.md#URL

---
name: enola.dev/id
doc: enola.md#ID
```

## Current Behavior

It does put a "red squiggle" on the first `doc: enola.md#URL` but not on the second `doc: enola.md#ID`.

In fact the 2nd `name: enola.dev/id` doesn't have the "hover" with the `description`from the schema either.

It looks like the YAML `---` syntax for _"multiple documents within a single stream"_ isn't supported / doesn't work?

## Expected Behavior

I expected it to flag the `doc` attribute as red in both my _URL_ and _ID_ attributes.
